### ISSUE TITLE
pmwebd service instructions?

### ISSUE THREAD

**Issue by onionjake** [Netflix/vector#10]
The instructions state that the `pmwebd` service needs to be running, but after following the instructions to compile from source there is no pmwebd service.  How do I install the 'pmwebd' service?

**Comment by spiermar** [comment]
@fche any comments?

**Comment by fche** [comment]
@onionjake, pmwebd has a few build prerequisites you may have missed, namely libmicrohttpd-dev.

**Comment by onionjake** [comment]
@fche I've tried installing `libmicrohttpd-dev` and still no luck.  Is there a list of the dependencies somewhere?

**Comment by onionjake** [comment]
Perhaps I just need `ENABLE_WEBAPI=true` on both make steps?

**Comment by fche** [comment]
The /debian/control file lists them if you're on that flavour; or on God's Own Distro `yum-builddep -y pcp` :-)

**Comment by fche** [comment]
(But if your distro has pcp but no pmwebd, open a bug with them to request it there.  You shouldn't have to build your own pcp.)

**Comment by onionjake** [comment]
I was also missing `libcairo2-dev`.

I was able to discover what was missing by passing `--with-webapi` to the `./configure` step.  This caused it to fail on missing dependencies.

**Comment by fche** [comment]
The cairo stuff is designed to be an optional dependency; you should still get a pmwebd suitable for vector use without it.

**Comment by scotte** [comment]
On a debian-based distro you should be able to use "apt-get build-dep pcp" to get all the dependencies required to build pcp.
