### ISSUE TITLE
Change the context expiration

### ISSUE THREAD

**Issue by nhproject** [Netflix/vector#107]
Hi,

Is it possible to change the duration of context? (make it larger)
[Wed Dec  2 13:12:21] pmwebd(85443): context PM_CONTEXT_HOST localhost (HOSTNAME) ( web***594409074***=pm1 ) created, ***expires after 300s***

**Comment by lberk** [comment]
You could modify the pmwebd configuration file (typically somewhere around /etc/pcp/pmwebd/pmwebd.options) and adding an `OPTIONS="$OPTIONS -t NNN" ` line, where N is the max number of seconds before a timeout on a web context (man pmwebd for details).

**Comment by spiermar** [comment]
Thanks @lberk ! Does that solve your problem @nhproject ? Also, Vector has a timeout hardcoded to 600s right now. Feel free to send a PR if you decide to make it configurable.

https://github.com/Netflix/vector/blob/master/src/app/services/dashboard.service.js#L143

**Comment by fche** [comment]
pmwebapi itself offers a control option.  When creating the /pmapi/context?...., add a  &polltimeout=MMMM  parameter to specify the number of seconds for timing out the context.

**Comment by spiermar** [comment]
Assuming this was resolved. Closing the issue. Reopen if necessary.
