### ISSUE TITLE
styling nit: excess margins / clipped numbers

### ISSUE THREAD

**Issue by fche** [Netflix/vector#108]
When the browser window is not quite the right size, one gets clipped window/interval numbers, like:
![foo](https://cloud.githubusercontent.com/assets/588885/11636101/44edf8d4-9d12-11e5-9de8-31fa7b73b442.png)

**Comment by spiermar** [comment]
Noticed that too. Still thinking about an decent solution for that since the inputs have fixed sizes. Probably something around limits on size that will change the input class from large to medium, small, and so on.

**Comment by spiermar** [comment]
![screen shot 2015-12-07 at 10 06 26 am](https://cloud.githubusercontent.com/assets/2207415/11639043/279fa922-9cdf-11e5-8f79-127dd7066dfd.png)

**Comment by hc000** [comment]
maybe the positioning of window and interval can be re-arranged and the hostname is in its own row?

**Comment by spiermar** [comment]
That's another option. Just break line (like mobile devices) a bit earlier.

**Comment by spiermar** [comment]
Thanks to @tregoning ;-)
