### ISSUE TITLE
containers disabled in 1.0.3, but containers.cgroup metric still fetched

### ISSUE THREAD

**Issue by fche** [Netflix/vector#109]
Just a performance nit.

**Comment by spiermar** [comment]
Fixed on https://github.com/Netflix/vector/commit/432f797e2c6c9938f63693088c377e82f2e2177a. Updated tags.

**Comment by fche** [comment]
Thanks for the quick fix!  With 1.0.3 retagged, do you plan to update the bintray binaries?

**Comment by spiermar** [comment]
Yes, doing that right now.

- Martin
