### ISSUE TITLE
Vector's embedded URL only allow use of metrics already being graphed

### ISSUE THREAD

**Issue by wcohen** [Netflix/vector#110]
I was experimenting the embedded URL that vector provides for graphs and it appears that it only allow use of metrics that are already being plotted.  Thus, when pmwebd is running something like following works fine

http://localhost:44323/vector/index.html#/embed?widgets=kernel.percpu.cpu,kernel&host=localhost:44323&hostspec=localhost

However, even though mem.util.available can be fetched via pmwebd something for a metric that is not on one of the existing vector plots does not work:

http://localhost:44323/vector/index.html#/embed?widgets=mem.util.available&host=localhost:44323&hostspec=localhost

Shouldn't vector allow gathering of any valid metric not just one on a limited menu?

**Comment by spiermar** [comment]
The widget names can lead to some confusion. What you have on the URL is a list of widgets, that purposively are named after the PCP metrics they use, but are not the same thing. 

For example, the 'network.tcpconn' widget uses 'network.tcpconn.established', 'network.tcpconn.time_wait' and 'network.tcpconn.close_wait'.
You can load a widget, but not a metric directly.

An 'ad-hoc' metric widget is in the roadmap (see #90), but was not implemented yet. What I have in mind is something like:

```
?widgets=ad.hoc(mem.util.available, pcp.metric.2, pcp.metric.3),widget.2,widget.3
```

Does that answer your question?

**Comment by wcohen** [comment]
Thanks for the explanation.  So the names in the embedded URL don't directly really refer to a pcp metric but the label for a widget.  The widgets just happen to be using the same names as pcp metrics.   So for the time being embed things are limited to the widgets list on the menu until #90 is address?

**Comment by spiermar** [comment]
That is correct, but simple widgets are easy to implement too.

https://github.com/Netflix/vector/wiki/Widgets

It's just a matter of describing it in the app.widgets.js file. For mem.util.available it should look like this:

```
{
                name: 'mem.util.available',
                title: 'Memory Utilization (Available)',
                directive: 'line-time-series',
                dataAttrName: 'data',
                dataModelType: MetricDataModel,
                dataModelOptions: {
                    name: 'mem.util.available'
                },
                size: {
                    width: '25%',
                    height: '250px'
                },
                enableVerticalResize: false,
                group: 'Memory'
            }
```
