### ISSUE TITLE
Unspecified error, No data plotting

### ISSUE THREAD

**Issue by kevinjpickard** [Netflix/vector#111]
I apologize if this seems like a simple problem, but I've been wrestling with it and I can't seem to get it to work. I have my own dedicated server running Ubuntu Server 14.04 LTS. I would like to use Vector to be able to see, in real-time or near real-time the performance impacts of what I am doing on the server. Vector seemed to be perfect.

So I built and installed from the source as described in the wiki (https://github.com/Netflix/vector/wiki/Installing-Performance-Co-Pilot) and then unzipped vector to /var/www/vector (I have nginx installed). I then navigated to http://IP/vector on my desktop. I get the Vector GUI, but no data. 
![capture](https://cloud.githubusercontent.com/assets/8092171/12910843/46adef18-cecb-11e5-957a-32405766311e.PNG)
For the hostname I enter IP:44343. I have tried the IP without the port specified as well. I've restarted the appropriate services on the server, but that did not help. 

I can't seem to find the appropriate log files to see what it happening, and I'm not sure what the next troubleshooting step is. I've done some google searches, but everything that comes up seems to be different errors. I also don't really know what to search because I don't know what log files to reference to pull exact errors from. Any ideas?

**Comment by fche** [comment]
Vector's error diagnostics could use some improvement. :-)
But anyway, data comes from performance co-pilot servers underneath; do you have pmwebd & pmcd running?

**Comment by fche** [comment]
See also https://bintray.com/pcp/trusty/pcp/view#files ... though I don't know where the webapps (which include a bundled snapshot of vector) are.

**Comment by spiermar** [comment]
@kevinjpickard what exactly happens when you type in the ip:port? From your screenshot I can see that Vector could not get a context from PCP. Did you get any error messages in the UI after some time (timeout)? Can you check the JavaScript console and share the messages?

**Comment by kevinjpickard** [comment]
@fche, yes both pmwebd and pmcd are running. 

@spiermar, Initially I got a generic red bar with "Error!" text, but I've been messing with it, and now nothing happens after the timeout. I've reinstalled PCP once or twice, but it doesn't seem to make a difference.

**Comment by kevinjpickard** [comment]
So I've been playing around with this more. When I guide my browser to http://<hostIP>:44323/pmapi/2102034630/_fetch?names=hinv.ncpu I get the message "PMWEBD error, code -12376: Attempt to use an illegal context"

**Comment by kevinjpickard** [comment]
I have been following some of the same steps as this issue: https://github.com/performancecopilot/pcp/issues/14 and I believe my issue might be related, despite the different error message. I'll continue down this path and report back.

**Comment by fche** [comment]
The /pmapi/NNNNN/ number is transient, so you can't indefinitely reuse one.  Try inspecting the /var/log/pcp/pmwebd/pmwebd.log file for advice.   Try fetching the pcp webapps via git from https://github.com/performancecopilot/pcp-webjs.git to under /usr/share/pcp/webapps - that will include vector and some other simpler applications.  Try checking the browser javascript console and/or web debugger's network logs.

**Comment by spiermar** [comment]
Looks like the first call to fetch context failed. What Vector does is that after you enter the hostname, it tries to generate a new context. Once the new context is returned, it starts to use it to fetch the metrics. If there's an error fetching the context, the error message would appear and after 5 sec, disappear, but it will still be in the JavaScript console on your browser.
With the console logs and the response from that first call, we can probably pinpoint the issue.

**Comment by spiermar** [comment]
Since there was no reply. I'm assuming this issue is resolved. Reopen if necessary.
