### ISSUE TITLE
Feature request: add ability to resize widget "snapped" to the grid

### ISSUE THREAD

**Issue by portante** [Netflix/vector#112]
With a four across grid by default, it would be great to resize widgets to exactly fit in the grid so that I can avoid oversizing or undersizing watching my other widgets move around unintentionally.

**Comment by spiermar** [comment]
@portante is that what you are looking for?

https://github.com/Netflix/vector/issues/5

**Comment by portante** [comment]
Yes, that would do it.  Thanks!
