### ISSUE TITLE
SIGWINCH causes vector to exit

### ISSUE THREAD

**Issue by hfaran** [Netflix/vector#118]
```bash
$ sudo docker run -it -p 9020:80 mspier/vector
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Fri Apr 01 19:26:17.329013 2016] [mpm_event:notice] [pid 1:tid 140440386754432] AH00489: Apache/2.4.18 (Unix) configured -- resuming normal operations
[Fri Apr 01 19:26:17.329325 2016] [core:notice] [pid 1:tid 140440386754432] AH00094: Command line: 'httpd -D FOREGROUND'
[Fri Apr 01 19:26:24.307892 2016] [mpm_event:notice] [pid 1:tid 140440386754432] AH00492: caught SIGWINCH, shutting down gracefully
```

That is, resizing the terminal window, which sends SIGWINCH to the process causes it to shut down. Just a guess but I don't **think** this is the desired behaviour. ;)

**Comment by spiermar** [comment]
That's probably related to https://github.com/docker-library/httpd/issues/9. Apparently its a consequence in running in interactive mode. Can you try detaching? "-d" instead of  "-it"?

**Comment by hfaran** [comment]
Ah. Maybe this is worth mentioning in the Getting Started wiki then? Because that's the command that the documentation gives.

**Comment by spiermar** [comment]
I'll add a note there. Thanks!

**Comment by spiermar** [comment]
Updated the wiki. https://github.com/Netflix/vector/wiki/Getting-Started ;-)
