### ISSUE TITLE
'No available data' showing for all charts

### ISSUE THREAD

**Issue by meteorfox** [Netflix/vector#12]
After building PCP from source, and installing on Ubuntu 14.04, once I load the webapp and type-in the hostname, it finds the host, but charts stay with 'No available data' label.

I built and configured pcp with these commands
```bash 
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-webapi
make
make install
```
after that I started pmcd, pmlogger, and pmwebd services, using update-rc.d and service.

When I enter the host, I can see the HTTP request `http://<host>:44323/pmapi/context?hostspec=localhost&polltimeout=600` firing and succeeding in  DevTools, charts refresh, but they show no data.

Any thoughts?

**Comment by fche** [comment]
Are you seeing valid-looking numeric data come back from the pmapi json services?

**Comment by pforai** [comment]
Same issue here! Same platform, same install of pcp.

**Comment by spiermar** [comment]
Can you check the JavaScript console? Any errors? What's the response from PCP for the fetch request (<host>/pmapi/_fetch?names=<metrics>)?

**Comment by smedefind** [comment]
I'm having the same problem.

But the examples in webjs project are working.


```/pmapi/_fetch?names=``` returns an wrror for me.
```PMWEBD error, code -22: Invalid argument```

**Comment by pforai** [comment]
All looks well and as expected. Valid JSON, updating metrics. 

Example:
Calling http://localhost:44323/pmapi/1796559532/_metric?prefix=hinv
Output:
```json
{ "metrics":[
{"name":"hinv.physmem","text-oneline":"total system memory metric from /proc/meminfo","text-help":"total system memory metric from /proc/meminfo","pmid":251659273,"sem":"discrete","units":"Mbyte","type":"U32"},
{"name":"hinv.pagesize","text-oneline":"Memory page size","text-help":"The memory page size of the running kernel in bytes.","pmid":251659275,"sem":"discrete","units":"byte","type":"U32"},
{"name":"hinv.ncpu","text-oneline":"number of CPUs in the system","text-help":"number of CPUs in the system","pmid":251658272,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.ndisk","text-oneline":"number of disks in the system","text-help":"number of disks in the system","pmid":251658273,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.nfilesys","text-oneline":"number of (local) file systems currently mounted","text-help":"number of (local) file systems currently mounted","pmid":251663360,"sem":"discrete","units":"count","type":"U32"},
{"name":"hinv.ninterface","text-oneline":"number of active (up) network interfaces","text-help":"number of active (up) network interfaces","pmid":251661339,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.nlv","text-oneline":"number of logical volumes","text-help":"number of logical volumes","pmid":251711489,"indom":251658262,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.nnode","text-oneline":"number of NUMA nodes in the system","text-help":"number of NUMA nodes in the system","pmid":251658259,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.machine","text-oneline":"machine name, IP35 if SGI SNIA, else simply linux","text-help":"machine name, IP35 if SGI SNIA, else simply linux","pmid":251676679,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.map.scsi","text-oneline":"list of active SCSI devices","text-help":"There is one string value for each SCSI device active in the system,\u000Aas extracted from /proc/scsi/scsi. The external instance name\u000Afor each device is in the format scsiD:C:I:L where\u000AD is controller number, C is channel number, I is device ID\u000Aand L is the SCSI LUN number for the device. The values for this\u000Ametric are the actual device names (sd[a-z] are SCSI disks, st[0-9]\u000Aare SCSI tapes and scd[0-9] are SCSI CD-ROMS.","pmid":251673600,"indom":251658251,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.map.cpu_num","text-oneline":"logical to physical CPU mapping for each CPU","text-help":"logical to physical CPU mapping for each CPU","pmid":251676678,"indom":251658240,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.map.cpu_node","text-oneline":"logical CPU to NUMA node mapping for each CPU","text-help":"logical CPU to NUMA node mapping for each CPU","pmid":251676680,"indom":251658240,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.map.lvname","text-oneline":"mapping of logical volume names for devices","text-help":"Provides a logical-volume-name to device-name mapping for the device\u000Amapper subsystem.","pmid":251711488,"indom":251658262,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.map.dmname","text-oneline":"per-device-mapper device persistent name mapping to dm-[0-9]*","text-help":"per-device-mapper device persistent name mapping to dm-[0-9]*","pmid":251713549,"indom":251658264,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.cpu.clock","text-oneline":"clock rate in Mhz for each CPU as reported by /proc/cpuinfo","text-help":"clock rate in Mhz for each CPU as reported by /proc/cpuinfo","pmid":251676672,"indom":251658240,"sem":"discrete","units":"count","type":"FLOAT"},
{"name":"hinv.cpu.vendor","text-oneline":"manufacturer of each CPU as reported by /proc/cpuinfo","text-help":"manufacturer of each CPU as reported by /proc/cpuinfo","pmid":251676673,"indom":251658240,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.cpu.model","text-oneline":"model number of each CPU as reported by /proc/cpuinfo","text-help":"model number of each CPU as reported by /proc/cpuinfo","pmid":251676674,"indom":251658240,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.cpu.stepping","text-oneline":"stepping of each CPU as reported by /proc/cpuinfo","text-help":"stepping of each CPU as reported by /proc/cpuinfo","pmid":251676675,"indom":251658240,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.cpu.cache","text-oneline":"primary cache size of each CPU as reported by /proc/cpuinfo","text-help":"primary cache size of each CPU as reported by /proc/cpuinfo","pmid":251676676,"indom":251658240,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.cpu.bogomips","text-oneline":"bogo mips rating for each CPU as reported by /proc/cpuinfo","text-help":"bogo mips rating for each CPU as reported by /proc/cpuinfo","pmid":251676677,"indom":251658240,"sem":"discrete","units":"","type":"FLOAT"},
{"name":"hinv.cpu.model_name","text-oneline":"model name of each CPU as reported by /proc/cpuinfo","text-help":"model name of each CPU as reported by /proc/cpuinfo","pmid":251676681,"indom":251658240,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.cpu.flags","text-oneline":"Hardware capability flags for each CPU as reported by /proc/cpuinfo","text-help":"Hardware capability flags for each CPU as reported by /proc/cpuinfo","pmid":251676682,"indom":251658240,"sem":"discrete","units":"","type":"STRING"},
{"name":"hinv.cpu.cache_alignment","text-oneline":"Cache alignment for each CPU as reported by /proc/cpuinfo","text-help":"Cache alignment for each CPU as reported by /proc/cpuinfo","pmid":251676683,"indom":251658240,"sem":"discrete","units":"","type":"U32"},
{"name":"hinv.cpu.online","text-oneline":"CPU online state from /sys/devices/system/cpu/*/online","text-help":"CPU online state from /sys/devices/system/cpu/*/online","pmid":251714560,"indom":251658240,"sem":"instant","units":"","type":"U32"},
{"name":"hinv.node.online","text-oneline":"NUMA node online state from /sys/devices/system/node/*/online","text-help":"NUMA node online state from /sys/devices/system/node/*/online","pmid":251714561,"indom":251658259,"sem":"instant","units":"","type":"U32"}]}
```

**Comment by pforai** [comment]
@smedefind You need to pass query with a context number as well. See http://manpages.ubuntu.com/manpages/saucy/man3/PMWEBAPI.3.html section "Context Creation".

**Comment by spiermar** [comment]
What's the request URL? What names are being requested?

**Comment by fche** [comment]
e.g., a firefox FireBug "net" activity monitor should show the full pmapi request & response; would be very informative.  Another source of data is the pmwebd log file (`/var/log/pcp/pmwebd/pmwebd.log`), made even more informative if pmwebd is invoked with a few `-v` verbose flags.

**Comment by pforai** [comment]
@spiermar Funny thing is that I dont see any query from Vector being done, only the ones I was doing from Chrome to look at the JSON output myself.

**Comment by smedefind** [comment]
@pforai Thanks, your link with a current context does work for me.

**Comment by fche** [comment]
The _metric query is for metadata; _fetch is the one where actual data, like spice, should flow.

**Comment by meteorfox** [comment]
Manually doing the HTTP request for
`http://<host>:44323/pmapi/2102034630/_metric?prefix=hinv`
returns a JSON response with data.

But looking at the Network tab in Chrome, Vector never does this request.

**Comment by smedefind** [comment]
I'm only seeing a request for ```http://localhost:44323/pmapi/context?hostspec=localhost&polltimeout=600```.
I get a context number back, but no other requests are made.

**Comment by fche** [comment]
@smedefind, javascript console then is where I'd go ...

**Comment by pforai** [comment]
@fche Also fetching the real metrics from Chrome works, for example:
```json
{"timestamp":{"s":1428527507,"us":851111 }, "values":[{"pmid":251658278,"name":"disk.dev.read_bytes","instances":[
{"instance":0, "value":452145 }]}]}
```

**Comment by meteorfox** [comment]
Also running this HTTP request manually also works for me:
`http://<host>:44323/pmapi/2102034630/_fetch?names=hinv.ncpu`

Outputs:
```json

{"timestamp":{"s":1428527450,"us":445181 }, "values":[{"pmid":251658272,"name":"hinv.ncpu","instances":[
{"instance":-1, "value":24 }]}]}
```

But again, Vector never issues a similar HTTP request.

**Comment by smedefind** [comment]
@fche I haven't seen any errors in the console since I got pmwebd working.

**Comment by fche** [comment]
Have you tried another web browser by any chance?

**Comment by meteorfox** [comment]
@fche I tried Firefox, same issue.

**Comment by pforai** [comment]
The only thing that the console shows is that it cant talk to the auto update port:

````
The connection to ws://localhost:35729/livereload was interrupted while the page was loading. livereload.js:193:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.min.js:3:7532
window.controllers is deprecated. Do not use it for UA detection. controllers.js:48:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
"Dashboard controller initialized with / view." angular.min.js:102:324
"Loading default dashboard." angular.min.js:102:324
"Host: localhost" angular.min.js:102:324
"Host updated." angular.min.js:102:324
"Context updated." angular.min.js:102:324
"total" 1012 nv.d3.min.js:1:747
```

**Comment by fche** [comment]
Are y'all typing "localhost" into the vector target-selector window?
Another thing to try out is to use pmwebd itself to serve the vector app/ files, rather than a python or whatnot intermediary:
  # kill the system pmwebd
  # /usr/libexec/pcp/bin/pmwebd -v -v -R /path/to/vector/app

**Comment by pforai** [comment]
Yes, just localhost - now that the live reload port works I can see a GET to http://localhost:44323/pmapi/context?hostspec=localhost&polltimeout=600 - but there is no context returned.

Headers:
````
Host: localhost:44323
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
Accept: application/json, text/plain, */*
````

And it answers with a valid JSON context ID.

But nothing happens from then on ...

**Comment by smedefind** [comment]
I've tried sharing it via the pmwebd webapps folder too. Same problem.

Console has the following
```
 Dashboard controller initialized with / view.
angular.js:11655 Loading default dashboard.
angular.js:11655 Host: ops-jenkins-slave-001.optoro.io
angular.js:11655 Host updated.
angular.js:11655 Context updated.
nv.d3.min.js:1 total 320
```

**Comment by Lucius-** [comment]
Same issue here. Vector only makes a call to `http://<HOST>:44323/pmapi/context?hostspec=localhost&polltimeout=600` but never makes any subsequent calls that I can see. Chrome's javascript console looks like:

>Dashboard controller initialized with / view.
>angular.js:11655 Loading default dashboard.
>angular.js:11655 Host: 192.168.110.211
>angular.js:11655 Host updated.
>angular.js:11655 Context updated.
>nv.d3.min.js:1 total 290

I can see pmwebd get the initial request for a context from Vector in /var/log/pcp/pmwebd/pmwebd.log, but nothing happens after that.

**Comment by meteorfox** [comment]
Here's a few things I tried.

Under the JS console in Chrome, I loaded the `MetricListService`, and the `DashboardService`, as follows:

```javascript
injector = angular.element(document.body).injector();
metrics = injector.get('MetricListService');
dashboard = injector.get('DashboardService');
```

Then after that, I executed the following:

```javascript
dashboard.updateContext()   // Load the context, works OK
metrics.updateMetrics()   // Get 400 error
```
updateMetrics() fires this request:
```
http://<private_ip>:44323/pmapi/1158735017/_fetch?names=kernel.all.cpu.sys,kernel.all.cpu.user,hinv.ncpu,kernel.percpu.cpu.sys,kernel.percpu.cpu.user,kernel.all.runnable,kernel.all.load,network.interface.in.bytes,network.interface.out.bytes,network.tcpconn.established,network.tcpconn.time_wait,network.tcpconn.close_wait,network.interface.in.packets,network.interface.out.packets,network.tcp.retranssegs,network.tcp.timeouts,network.tcp.listendrops,network.tcp.fastretrans,network.tcp.slowstartretrans,network.tcp.syncretrans,mem.util.cached,mem.util.used,mem.util.free,mem.util.bufmem,mem.vmstat.pgfault,mem.vmstat.pgmajfault,kernel.all.pswitch,disk.dev.read,disk.dev.write,disk.dev.read_bytes,disk.dev.write_bytes,disk.dev.avactive,disk.dev.read_rawactive,disk.dev.write_rawactive
```

but then in it's response it says the following:

`PMWEBD error, code -12366: IPC protocol failure`

**Comment by smedefind** [comment]
I repeated @meteorfox javascript and started getting a couple graphs. Each time I run updateMetrics() I get a new data point.

But the console has the following stacktrace
```
 TypeError: undefined is not a function
    at services.js:185
    at angular.js:9408
    at angular.js:13248
    at n.$get.n.$eval (angular.js:14466)
    at n.$get.n.$digest (angular.js:14282)
    at n.$get.n.$apply (angular.js:14571)
    at l (angular.js:9698)
    at M (angular.js:9888)
    at XMLHttpRequest.F.onload (angular.js:9829)
```

**Comment by meteorfox** [comment]
@smedefind Did you also get a 400 for the /_fetch request, or just the TypeError?

**Comment by smedefind** [comment]
@meteorfox Just the Type Error

**Comment by pforai** [comment]
Yeah, same for me - Type Error:
````
TypeError: undefined is not a function
    at services.js:185
    at angular.js:9408
    at angular.js:13248
    at n.$eval (angular.js:14466)
    at n.$digest (angular.js:14282)
    at n.$apply (angular.js:14571)
    at l (angular.js:9698)
    at M (angular.js:9888)
    at XMLHttpRequest.F.onload (angular.js:9829)
```

**Comment by fche** [comment]
The TypeError on a manual call to updateMetrics() is perhaps not wrong - it expects callback() to be given a parameter.
The -12366 error is more intriguing.  Does the pmwebd.log and/or pmcd.log elaborate?

**Comment by spiermar** [comment]
Checking. Probably an unhandled error.

**Comment by meteorfox** [comment]
@fche Yup, like you said, it throws undefined because it takes a callback. https://github.com/Netflix/vector/blob/f18ac8a0fb2026c3c3fb3a19f9a394c0f0de5ec6/app/js/services.js#L185

I solved the -12366 error by increasing the timeout for a `PMCD_REQUEST`. I noticed this because just before I got the -12366 error, it showed this error `[Wed Apr  8 22:00:09] pmwebd(40524): [10.7.40.93:56502] pmFetch failed: Timeout waiting for a response from PMCD` in the log.

So I went to `/etc/pcp/pmwebd/pmwebd.options` and updated this option:
`PMCD_REQUEST_TIMEOUT=10` which originally it was set to 1, restarted pmwebd, and the timeout error went away.

After I updated the pmwebd.options with the timeout increase, my javascript console example worked, and gathered a datapoint (just like the others said), but it doesn't continue to automatically update the charts for some reason.

**Comment by fche** [comment]
@meteorfox Ah well that's interesting ... even a 1-second response time is unusually long for pmcd.  Is the server super-busy, or has a great number of disk/processes/etc. ?

**Comment by spiermar** [comment]
@meteorfox if there's an exception, the metric fetch loop stops.

**Comment by meteorfox** [comment]
@fche The server is idle. There are only 351 processes, and 1 disk, with 2 partitions, and 1 partition has 4 LVM mounts.

**Comment by fche** [comment]
@meteorfox Thanks, it should be within the comfort range.  Could you try

    # strace -tt -p `pgrep pmcd`

around the time that the timed-out request is being serviced?

**Comment by meteorfox** [comment]
@spiermar I think I found the problem, on why is not updating.

This line:
https://github.com/Netflix/vector/blob/master/app/js/services.js#L274
checks for `$rootScope.properties.hostname` but there is no `hostname` property in that object, only `host` is defined.

@fche will try that now.

**Comment by meteorfox** [comment]
@spiermar yup, I change hostname -> host. Now it works.

**Comment by fche** [comment]
Nice work, Carlos.

**Comment by spiermar** [comment]
bingo! pushing the change! tks @meteorfox

**Comment by spiermar** [comment]
renamed that variable recently and probably missed this one. :-)

**Comment by meteorfox** [comment]
@fche I do have 25 network interfaces, that could be slowing it down when it fetches the in/out bytes for each of them

**Comment by meteorfox** [comment]
Thank you all @fche @spiermar  for your help.

I'll close once the change is up.

**Comment by fche** [comment]
@meteorfox That could be it.  Please consider pinging http://oss.sgi.com/bugzilla/show_bug.cgi?id=1067 with your cc:.

**Comment by spiermar** [comment]
https://github.com/Netflix/vector/commit/14477b92cb0bf968b3039b67744dcb32bda805fd

**Comment by Lucius-** [comment]
@meteorfox @spiermar That fixed it. Thanks!

**Comment by meteorfox** [comment]
@fche will do.

Confirmed that 14477b9 fixes the issue.

Thanks again for you help, and fast turnaround.
