### ISSUE TITLE
Use Array.prototype.filter instead of imperative mutation

### ISSUE THREAD

**Issue by dylanjohnson** [Netflix/vector#13]
This project looks great; got lots of ideas, but want to start with a small change.

This PR would use a functional approach for the `groupFilter` via `Array.prototype.filter` instead of imperatively creating a new array. Something like:

```js
filters.filter('groupFilter', function () {
    function itemIsInGroup(item) {
        return item.group === this;
    }

    return function (collection, group) {
        return collection.filter(itemIsInGroup, group);
    }
});
```

If this sounds good, please assign the issue to me and I'll submit a PR.

**Comment by spiermar** [comment]
@dylanjohnson can't assign you since you're not in the collab list, but feel free to send the pull request! :-)
