### ISSUE TITLE
Documentation on how to enable CPU flame graph in Vector

### ISSUE THREAD

**Issue by sattishv** [Netflix/vector#134]
Hi team,

Do we have any documentation link on how to generate CPU Flame Graphs from Vector Web Interface. 
It looks like we need to have few tools like perf-map-agent , flamegraph-pmda as prerequisite. Could you please direct us to the doc links

Thanks
Sattish.

**Comment by spiermar** [comment]
There's no official documentation because flame graphs depend on an extra PMDA. I published the code a while ago, but it's far from ideal. I've been meaning to implement a better solution, but lacking bandwidth recently. I can try creating some basic documentation around it.

**Comment by sattishv** [comment]
Hi Team,

Thanks for the response. Appreciate your commitment. Meantime let me try installing the prerequisites Please let us know once you have the basic docs.

Thanks
Sattish

**Comment by spiermar** [comment]
README was updated in the PMDA repo.

https://github.com/spiermar/generic-pmda

Once the PMDA is working, just set the `enableCpuFlameGraph` option to `true` in the `index.config.js` file.
