### ISSUE TITLE
documentation for installation from debs is wrong

### ISSUE THREAD

**Issue by vavrusa** [Netflix/vector#136]
The [documentation](http://vectoross.io/docs/installing-performance-co-pilot.html) says the packages are now on bintray.com

> Debian (Jessie):
>
> $ echo "deb https://dl.bintray.com/netflixoss/jessie jessie main" | sudo tee -a /etc/apt/sources.list
> Once that is done, you should be able to update your package list:
> $ sudo apt-get update

However apt-get update fails:

```bash
$ sudo apt-get update
...
W: Failed to fetch https://dl.bintray.com/netflixoss/jessie/dists/jessie/main/binary-amd64/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Looking at the bintray.com it looks like the packages were moved elsewhere: https://bintray.com/pcp/jessie/pcp

**Comment by spiermar** [comment]
Tks for the report @vavrusa ! Just pushed a doc change. Should be good now.
