### ISSUE TITLE
msie11 "compatibility view" incompatible with vector

### ISSUE THREAD

**Issue by fche** [Netflix/vector#138]
In msie11's default "display intranet sites in compatibility view" mode, vector is prevented from running.  Our index.html file should include some trickery to make sure msie11 uses normal mode, in which case it seems to work okay.  One possible way is with a <meta> tag at the top:

http://stackoverflow.com/a/26463309/661150

**Comment by spiermar** [comment]
I can add it, but will probably need a VM to test this. Don't think anyone around here has IE.

**Comment by spiermar** [comment]
Can you try @fche

https://github.com/Netflix/vector/commit/fa23cc32745caf3448b641892b67d18d7a659314

**Comment by spiermar** [comment]
Assuming it's working. Closing the issue.
