### ISSUE TITLE
Time calculation should be calculated by pcp metric metadata instead of hard coded

### ISSUE THREAD

**Issue by hc000** [Netflix/vector#140]
example to get meta data

`http://host:44323/pmapi/121221794/_metric?prefix=kernel.all.cpu.user`

`{ "metrics":[
{"name":"kernel.all.cpu.user","text-oneline":"total user CPU time from /proc/stat for all CPUs, including guest CPU time","text-help":"total user CPU time from /proc/stat for all CPUs, including guest CPU time","pmid":251658260,"sem":"counter","units":"millisec","type":"U64"}]}`

using the units section to determine time.

affected metrics:
https://github.com/performancecopilot/pcp/blob/master/src/pmdas/windows/pmda.c#L25

documentation
http://pcp.io/man/man3/pmwebapi.3.html
METRIC METADATA

**Comment by spiermar** [comment]
Duplicate of #82
