### ISSUE TITLE
Vector shows nothing

### ISSUE THREAD

**Issue by sebelk** [Netflix/vector#145]
Hi,

Vector shows nothing at all:

![Vector](https://cloud.githubusercontent.com/assets/4109256/26223584/25adb346-3bf5-11e7-83f7-a2c41f45b135.png)

I have the docker container:
```
docker ps -f status=running 
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                NAMES
00e37e28c6eb        netflixoss/vector:latest   "/usr/bin/caddy -root"   10 minutes ago      Up 10 minutes       0.0.0.0:80->80/tcp   vector
```
You can take a look about details at https://pastebin.com/BsxMv394

Also:

```
tcp        0      0 0.0.0.0:44321           0.0.0.0:*               LISTEN      23525/pmcd          
tcp        0      0 0.0.0.0:44323           0.0.0.0:*               LISTEN      23041/pmwebd        
tcp        0      0 0.0.0.0:4331            0.0.0.0:*               LISTEN      404/pmlogger        
tcp6       0      0 :::44321                :::*                    LISTEN      23525/pmcd          
tcp6       0      0 :::44323                :::*                    LISTEN      23041/pmwebd        
tcp6       0      0 :::4331 
```

My OS:

```
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 25 (Twenty Five)
Release:        25
Codename:       TwentyFive
```
Am I doing something wrong?

Thanks in advance!

**Comment by fche** [comment]
Check out the pmwebd.log file's contents.  Check out the web browser's javascript / network console.  Check that you set a "Hostname" - that is what tells the web browser where to find the pmwebd daemon.

**Comment by spiermar** [comment]
In the screenshot, target hostname is not filled (like @fche mentioned), so UI is "disconnected" from PCP. You have to type in the hostname (or ip) from the server you want to monitor.

**Comment by spiermar** [comment]
@sebelk assuming that was the issue. Closing it. Let me know if that is not the case and I'll reopen it.
