### ISSUE TITLE
Demo is broken?

### ISSUE THREAD

**Issue by sitsofe** [Netflix/vector#146]
Looking at http://vectoross.io/demo/ doesn't actually show any graphs only place holders for graphs (at least in Chrome)...

**Comment by spiermar** [comment]
@sitsofe which server running PCP are you trying to fetch metrics from?

**Comment by sitsofe** [comment]
Oh! I hadn't twigged it was "live" and needed to pull data from a real pcp server. Let me close this issue before anyone else notices...
