### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by sammcj** [Netflix/vector#15]
Great work guys/gals!

Any plans to release an official Docker image for Vector?

**Comment by spiermar** [comment]
Yes. We're planning a ZeroToVector image!

**Comment by sammcj** [comment]
Great! May I suggest basing it on the debian/jessie Docker base image or a Python 3 specific subset of that?

That image is lightweight and has very good default behaviour, much better than say the Ubuntu images that are in the wild.

**Comment by spiermar** [comment]
Assigning @aspyker since he will probably work on that with me.

**Comment by mtrofimm** [comment]
:+1:

**Comment by spiermar** [comment]
Dockerfile is done. https://github.com/Netflix/vector/commit/d33fd9bc080bcf99a2dcdee1955f128d8228919f
Just waiting for the official image to be built and published to Docker Hub (netflixoss/vector).
