### ISSUE TITLE
PCP 3.10+ dependancy is painful

### ISSUE THREAD

**Issue by sammcj** [Netflix/vector#16]
Relying on PCP 3.10 or newer is painful as it's not available for any linux distros at present.

Compiling PCP from source is not always straightforward and the packages (or at least the debs) available on their ftp server are i386 only.

Is it possible to bundle Vector with the PCP dependencies or perhaps provide a source for PCP packages?

**Comment by ersinesen** [comment]
Try installing 'bison' for pcp build error, after installing required ones.

**Comment by spiermar** [comment]
@fche do you think it would be interesting to create a PPA for deb packages at least? and something equivalent for RPMs?

**Comment by fche** [comment]
Fedora rawhide contains a weekly full build of git pcp, and we could consider a COPR for older-than-rawhide variants.  Perhaps other pcp folks with debian/ubuntu connections could undertake a PPA there.

**Comment by spiermar** [comment]
Let me talk with a few colleagues here. Perhaps we can create a PPA. Also, we can help push packages to be updated in the Canonical repos.

**Comment by spiermar** [comment]
Looks like a PPA is the way to go. Planning to get this done on Monday.

**Comment by sammcj** [comment]
Isn't a PPA for Ubuntu only? What about a standard Debian repo?

**Comment by spiermar** [comment]
Not necessarily. If the packages are compatible with Debian libraries, should work there too.

**Comment by scotte** [comment]
@sammcj is correct, PPA is (technically) Ubuntu specific. Installing from a PPA to vanilla Debian can be safe, or can be horribly bad due to dependencies (frankendistro).

I run Debian Wheezy and Jessie, so I'll validate that the .deb packages we publish don't cause any bad side effects for Debian. If it doesn't work cleanly, we'll work out another plan for distributing the vanilla .debs - maybe @fche can add amd64 .debs in the official PCP distribution as well (only i386 is there that I saw).

**Comment by kutchar** [comment]
+1 for the PPA

**Comment by spiermar** [comment]
Just checked and I can probably create a PPA and upload the amd64 packages for Trusty and maybe Precise. We're already building the packages and publishing to our internal repo, so just need to upload them to PPA too.

**Comment by kutchar** [comment]
@spiermar that'd be awesome!

**Comment by spiermar** [comment]
@fche Amer made a few changes to pmwebd back in September and did not push to pcpfans. 2 we really require. 1 that is a hack and can probably be ignored. Before risking making a mess, can I send you guys the diffs so you can have a look?

**Comment by sammcj** [comment]
I really love that you guys are considering this but I have to be honest and say that using a Ubuntu specific system has me quite worried.

Ubuntu as an operating system does not exhibit the same reliability or quality as Debian and their packaging and maintenance releases are often broken, untested or contain strange, non-standard 'Ubuntuisms'.

While this is neither the place nor time to discuss these issues I don't see any evidence of them going away.

Why not just provide a standard Debian repo on something like packagecloud or whatever that anyone can use regardless of if their using standard Debian or a distro that happens to use Apt like Ubuntu?

**Comment by spiermar** [comment]
I would go for the more "generic" solution as possible. I suggested PPA because we're already building Ubuntu packages anyway. What would be required to use packagecloud?

**Comment by kutchar** [comment]
@sammcj @spiermar I agree that a generic solution would be ideal, but if the ubuntu PPA is a low hanging fruit, it's a good starting point until the generic solution is in place.

**Comment by sammcj** [comment]
Packagecloud was just one example, it's just a hosted standard repository for apt, yum and rubygems.

While your packages may work on Debian or Ubuntu the idea of keeping them on a distro specific system that 'happens' to work if you paste the apt line into standard Debian not only sends the wrong message, but also leaves you open in the future to someone contributing to the Ubuntu PPA that has only tested it on Ubuntu because that's what a PPA is for.

I've seen many people put off by Ubuntu specific package repos because they've actually broken package dependencies over time as Ubuntu has their own packaging team and different versions of packages available in their repos (often older than what is in Debian Backports)

**Comment by sammcj** [comment]
I don't want to stop progress though so if it's easier for you to just do that and support it that way by all means do it - just be aware that some people will not use those packages / may have a harder time justifying use of the product because of it.

**Comment by sammcj** [comment]
@kutchar got you - go for it. I appreciate that you took the time to engaged in conversation around my concerns.

**Comment by kutchar** [comment]
@sammcj :)

**Comment by spiermar** [comment]
We can go with packagecloud too. Never used it, but seems simple enough. I can push the Ubuntu packages we already built and find some contributors for the other dist/versions.

**Comment by natoscott** [comment]
packagecloud.io looks good to me too - we had been looking for a solution like this (built in support for multiple distros) for the master pcp repo builds.  I'll try to get the pending pcp-3.10.4 release up there this week.

**Comment by natoscott** [comment]
re packagecloud.io, it looks like we wont be able to use that for PCP unless we can get some kind of sponsorship or funding - we have ~30 packages from just a default Debian build of PCP, which already tips us over the 25 package limit for the free service.  Its a good looking solution though - are there any others like that anyone here can recommend?

packagecloud.io might suit just fine for vector itself though, Martin, since that's just the one package (and its a noarch package too).

**Comment by spiermar** [comment]
Ok, got that sorted out! I can use our bintray.com account and publish the packages (Debian, Ubuntu, RPMs, etc). Will try to get it done early next week.

**Comment by sammcj** [comment]
bintray looks really nice - great find!

**Comment by natoscott** [comment]
+1 - thanks Martin!

**Comment by spiermar** [comment]
It's up!!

https://github.com/Netflix/vector/wiki/Installing-Performance-Co-Pilot

We have Ubuntu Trusty and Precise, amd64 already there. I'll add Debian Wheezy and i386 soon.

Let me know if the instructions work for you!

**Comment by natoscott** [comment]
Thanks Martin!

The manual-build-from-source install steps need these last few steps...

       # groupadd -r pcp
       # useradd -c "Performance Co-Pilot" -g pcp -d /var/lib/pcp -M -r -s /usr/sbin/nologin pcp

cheers.

**Comment by spiermar** [comment]
thanks @natoscott ! I'll add that!

**Comment by sammcj** [comment]
You guys are legends!

**Comment by spiermar** [comment]
thanks to @scotte for setting everything up at bintray. :-)

**Comment by SimonKberg** [comment]
This is fantastic! 

Would it be possible to add a build for Ubuntu Utopic (and probably prepare for Vivid which is due release this month) as well? I'm aware it's rapidly approaching its EOL, but as off now it's the latest stable ubuntu version.

**Comment by SimonKberg** [comment]
Btw @spiermar the steps from @natoscott has to come before `make install`

**Comment by spiermar** [comment]
Tks @SimonKberg ! Updated the wiki. 
We plan on releasing packages for newer Ubuntu versions too. I just need to get the VMs ready to build the packages.

**Comment by spiermar** [comment]
Rocking Debian Wheezy too! Both amd64 and i386.

echo "deb https://dl.bintray.com/netflixoss/debian wheezy main" | sudo tee -a /etc/apt/sources.list
echo "deb-src https://dl.bintray.com/netflixoss/debian wheezy main" | sudo tee -a /etc/apt/sources.list

Will update the wiki shortly!

**Comment by kutchar** [comment]
@spiermar I still need to build/install Vector manually, right? Only PCP is in the repo? Any plans to publish Vector in the repo too?

**Comment by spiermar** [comment]
@kutchar Vector is just a static web application and I expect most users would want to host it on an existing web server, like Apache or Nginx. The dist tarball is already on Bintray:

https://bintray.com/netflixoss/Vector/vector/view

And it's just a matter of downloading and uncompressing it. I can add this information to the wiki too.
I would prefer not to distribute a web server in a package with Vector, but again, if there's a need. :-)

**Comment by SimonKberg** [comment]
Hey guys, i ended up creating a daily build recipe for PCP on launchpad. The source code is imported daily from git, and in case any changes are found a new build will be created and uploaded to [my ppa](https://code.launchpad.net/~simon-kjellberg/+archive/ubuntu/pcp-daily).

You can easily add it to any Ubuntu Vivid, Utopic or Trusty release (i386 & amd64) if you have `software-properties-common` installed:

```shell
$ sudo apt-add-repository ppa:simon-kjellberg/pcp-daily
$ sudo apt-get update
$ sudo apt-get install pcp pcp-webapi -y
```

For some reason the build for Precise is failing so I've disabled it for now until I have time to properly investigate.

**Comment by kutchar** [comment]
@spiermar I didn't realize that. For some reason I thought it was a node.js webapp. I think it'd be great idea to add that information to the wiki too because currently we only have installation steps for PCP. Keep up the great work guys!

**Comment by spiermar** [comment]
Fair enough. I'll add a bit more information to the wiki. I'll upload the remaining deb packages to Bintray and if everything works fine, I'll close the issue, unless you feel there's more work to be done on improving this.

**Comment by kutchar** [comment]
@spiermar sounds good. I already deployed it to a couple of servers and things look good thus far.

**Comment by spiermar** [comment]
@kutchar just added some more info around deploying to a web server.

https://github.com/Netflix/vector/wiki/Getting-Started

Will push out Utopic packages today.

**Comment by fche** [comment]
(Considering how easily pmwebd can serve the static webapp itself, should it be listed on that getting-started page, perhaps even as the preferred method?)

**Comment by spiermar** [comment]
Since it's already "part of the package", I can add it to the wiki.

**Comment by spiermar** [comment]
Utopic is already on Bintray too.

https://bintray.com/netflixoss/ubuntu/pcp-utopic/view

Closing the issue.

**Comment by spiermar** [comment]
Trusty 32 bit is there.

**Comment by sammcj** [comment]
32bit? What is this - 1997?!

**Comment by scotte** [comment]
It's surprising, but a lot of folks are still installing 32bit Linux even though they have a 64bit capable processor. Why is anyone's guess - there's some misinformation out there that using a 64bit O/S will consume more memory or perform worse.

Fortunately building 32bit packages isn't too hard - lxc is great for setting up environments for this sort of thing, we can bootstrap a foreign Linux lxc container in a few minutes the first time, and in seconds thereafter. :-)
