### ISSUE TITLE
vector on https://

### ISSUE THREAD

**Issue by blue-eyed-devil** [Netflix/vector#166]
while i had vector on http all is working fine. once placed it on https some scripts were blocked by chrome browser. can you please make sure that it is calling all scripts with "//" only instead of "http://". Otherwise very handful thing. Thanks

**Comment by spiermar** [comment]
@blue-eyed-devil which scripts were blocked more specifically? The whole client should be loaded from the same host, using either http or https, depending on the web server configuration. The only requests hardcoded to http are the pmwebd requests to get metrics. In this case, we can't use `//` because pmwebd might not be running on the same web server and with the same connection type as the client.

**Comment by blue-eyed-devil** [comment]
Mixed Content: The page at 'https://vector.example.com/#/?widgets=kernel.all.cpu,kernel.percpu.cpu,kernel.all.runnable,kernel.all.load,network.interface.bytes,network.tcpconn,network.interface.packets,network.tcp.retrans,mem,mem.vmstat.pgfault,kernel.all.pswitch,disk.iops,disk.bytes,disk.dev.avactive,disk.dev.latency&host=server.example.com&hostspec=localhost' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://server.example.com:44323/pmapi/context?hostspec=localhost&polltimeout=600'. This content should also be served over HTTPS.

**Comment by spiermar** [comment]
That's the use case I mentioned before. `pmwebd` is running on a different host, using https or not, so I can't default to the same connection type as Vector's web server.
There's a `protocol` option that can be passed via query string to change the default from `http` to `https`. Can you try it?

```
https://vector.example.com/#/?widgets=kernel.all.cpu,kernel.percpu.cpu,kernel.all.runnable,kernel.all.load,network.interface.bytes,network.tcpconn,network.interface.packets,network.tcp.retrans,mem,mem.vmstat.pgfault,kernel.all.pswitch,disk.iops,disk.bytes,disk.dev.avactive,disk.dev.latency&host=server.example.com&hostspec=localhost&protocol=https
```

If that works, and all hosts you're monitoring are `https`, you can change the default in the `index.config.js` file:

```
'protocol': 'http', // PMWEBD protocol (http or https)
```

The query string option is not visible in the UI at the moment. But it should be simple to add it if necessary.

ps.: the flame graph requests are hardcoded to `http` right now, but I'll update it to use the same as other requests. This shouldn't affect you.

**Comment by natoscott** [comment]
@spiermar pmwebd doesn't support https - see the SECURITY section of pmwebd(1) man page, in the "encryption/confidentiality" section.

**Comment by spiermar** [comment]
@natoscott but it can run behind an https proxy, correct? that's my assumption with @blue-eyed-devil use case.

**Comment by natoscott** [comment]
@spiermar ah yes, it surely can.

**Comment by spiermar** [comment]
@blue-eyed-devil can you confirm you're running `pmwebd` behind a an `https` proxy?

**Comment by blue-eyed-devil** [comment]
I dropped you an email so check it pls

**Comment by spiermar** [comment]
Configuration issue. Closing.
