### ISSUE TITLE
/pmapi/context request canceled by browser

### ISSUE THREAD

**Issue by michfuer** [Netflix/vector#168]
Thanks so much to everyone for your efforts in providing this neat tool!

I've got a guest virtual machine with Ubuntu 14.04.4 installed, running on my mac laptop.

Installed PCP on the guest machine according to http://vectoross.io/docs/installing-performance-co-pilot.html

The web daemon and metric collector appear to be running
```
$ pcp
Performance Co-Pilot configuration on pe:

  platform: Linux pe 3.13.0-128-generic #177-Ubuntu SMP Tue Aug 8 11:40:23 UTC 2017 x86_64
  hardware: 1 cpu, 1 disk, 1 node, 2001MB RAM
  timezone: UTC
  services: pmcd pmwebd
      pmcd: Version 3.12.1-1, 7 agents, 4 clients
      pmda: root pmcd proc xfs linux mmv jbd2
  pmlogger: primary logger: /var/log/pcp/pmlogger/pe/20170821.10.31
      pmie: pe: /var/log/pcp/pmie/pe/pmie.log
```

Deployed Vector to the guest machine web docroot according to http://vectoross.io/docs/deploying-web-server.html
If I point the browser (Chrome) at `my.domain/vector/index.html` the Vector app loads.
For Hostname I add my.domain, and leave Hostspec as localhost

I get a `"Failed fetching context from host"` error.

This request (http://my.domain:44323/pmapi/context?hostspec=localhost&polltimeout=600) is getting canceled by Chrome.

Only see a few warnings in Console, no errors 
<img width="1273" alt="screen shot 2017-08-30 at 3 32 25 pm" src="https://user-images.githubusercontent.com/1760015/29893683-e318e9ee-8da0-11e7-900b-b68281ebec11.png">

Output of `/var/log/pcp/pmwebd/pmwebd.log`
<img width="828" alt="screen shot 2017-08-30 at 3 33 57 pm" src="https://user-images.githubusercontent.com/1760015/29893806-48819cb8-8da1-11e7-8e73-ce2a1256f22b.png">

```
$ sudo netstat -tulpn
   tcp        0      0 0.0.0.0:44321           0.0.0.0:*               LISTEN      682/pmcd
   tcp        0      0 0.0.0.0:44323           0.0.0.0:*               LISTEN      6792/pmwebd
```

Next I tried having pmwebd serve Vector ala http://vectoross.io/docs/running-pmwebd.html

The app loads alright in the browser but I still see the context request (http://192.168.50.82:44323/pmapi/context?hostspec=localhost&polltimeout=600) being canceled by Chrome
<img width="1194" alt="screen shot 2017-08-30 at 4 19 51 pm" src="https://user-images.githubusercontent.com/1760015/29893928-ae43d30e-8da1-11e7-8ba9-a3e60dc58346.png">

Any ideas on what to try next would be greatly appreciated. Thank you!

**Comment by spiermar** [comment]
That seems pretty odd. First time I'm seeing it. Does the same thing happen with other browsers? Have you tried `curt` request the context? There are a handful of reasons for Chrome do cancel the request, most related to giving up on trying to hit a host (previous DNS errors, 400s, etc) or DOM elements being removed before the request is completed.
Anything particularly different about this scenario? Which version of Vector?

**Comment by michfuer** [comment]
@spiermar 
I'm seeing same behavior with other browsers
Opera
<img width="1102" alt="vector_on_opera" src="https://user-images.githubusercontent.com/1760015/29977598-efbed228-8f0b-11e7-9379-59824adb59ba.png">

Firefox
<img width="1273" alt="vector_on_firefox" src="https://user-images.githubusercontent.com/1760015/29977622-0179dbde-8f0c-11e7-8a29-8f0bcbac63ef.png">

curl
```
michfuer@~  $ curl -v http://192.168.50.82:44323/pmapi/context?hostspec=localhost&polltimeout=600
[1] 51383
michfuer@~  $ *   Trying 192.168.50.82...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.50.82 port 44323 failed: Operation timed out
* Failed to connect to 192.168.50.82 port 44323: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to 192.168.50.82 port 44323: Operation timed out
```

I was digging through chrome://net-internals, of which I'm not very familiar, but comparing the canceled request with a successful one it seems the divergence begins with the `TCP_CLIENT_SOCKET_POOL_REQUESTED_SOCKET` event. A few more things happen in the successful request, e.g. `SOCKET_POOL_BOUND_TO_CONNECT_JOB` but in the case of the context request these things aren't happening
<img width="1266" alt="vector_chrome_internals" src="https://user-images.githubusercontent.com/1760015/29977979-53de3996-8f0d-11e7-8b09-a36375fef2ee.png">

If it was something like DOM elements being removed before the request is complete, than I would think it'd be Vector triggering that since pmwebd is strictly serving up just Vector ala 
`vagrant@pe:~$ /usr/lib/pcp/bin/pmwebd -v -v -R vector -p 8080`

For Vector version, scrolling to the bottom of /index.html I see
`Version: v1.1.0-3-gc851eac`

Thanks for the help!

**Comment by fche** [comment]
If `curl` gives a timeout, then something odd is happening with pmwebd (as distinct from the "cancellation" of the ajax request out of the webapp).  It'd be good to turn up pmwebd verbosity and check out what it's doing at the time of the `curl` attempt.  This aspect of pmwebd is single-threaded (and so is `pmcd`), so particularly slow operations from pcp can indeed time out.  That's rare though and vector usually knows to try the operation again.

**Comment by michfuer** [comment]
Ok, so something's going on with port 44323 in my environment. If I specify pmwebd to listen on 8080 via `$ /usr/lib/pcp/bin/pmwebd -v -v -R vector -p 8080`, than I can successfully retrieve a context value
```
michfuer@~  $ curl -v http://192.168.50.82:8080/pmapi/context?hostspec=localhost&polltimeout=600
[1] 53080
michfuer@~  $ *   Trying 192.168.50.82...
* TCP_NODELAY set
* Connected to 192.168.50.82 (192.168.50.82) port 8080 (#0)
> GET /pmapi/context?hostspec=localhost HTTP/1.1
> Host: 192.168.50.82:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 24
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Date: Fri, 01 Sep 2017 08:40:46 GMT
<
* Connection #0 to host 192.168.50.82 left intact
{ "context": 408647459 }
```
So if I'm serving Vector via pmwebd on 8080, than we wouldn't expect it to simultaneously be listening and responding on 44323 right? However, if I set pmwebd port to 44323, I get a timeout for Vector `http://192.168.50.82:44323/index.html` as well as the context request `curl -v http://192.168.50.82:44323/pmapi/context?hostspec=localhost&polltimeout=600`

I started monitoring 192.168.50.82 with `tcpdump` and the initial packets never get an acknowledgement from the host on 44323, like nothing's listening even though `netstat` claims pmwebd is.

I've also been trying some different configs using http://pcp.io/man/man1/pmwebd.1.html thinking maybe there's some authentication mechanism I'm missing, but nothing's really standing out.

**Comment by michfuer** [comment]
So it turns out the INPUT chain of iptables on the monitored host was filtering out packets to port 44323. After flushing the chain I was able to `curl` a context value.

However, I was unable to get a context when pmwebd serves Vector from port 8080 as suggested in http://vectoross.io/docs/running-pmwebd.html, but working good if served from 44323
<img width="1171" alt="vector_pmwebd_port_44323" src="https://user-images.githubusercontent.com/1760015/30032990-9e546652-9166-11e7-9447-c8c4ca6b8504.png">

So before closing this issue does it make sense to update the documentation (I'd create a PR, but not sure if I can), or make the context request not hardcoded to 44323, but rather include port in the Hostname field or some such?

**Comment by spiermar** [comment]
The web server hosting Vector (pmwebd or not) is completely independent from the host you are trying to monitor. It might be the same, but for most users, it's not. Vector is a purely client-side application and port is not hardcoded. If you're running pmwebd on a non-standard port, in the host you are trying to monitor, you should specify that as documented [here](http://vectoross.io/docs/pcp-deployment-models.html), with `host:port`. I believe it was not entirely clear that you don't have to host Vector in the same host you are trying to monitor. If you have any documentation suggestions, feel free to submit a PR to https://github.com/spiermar/vectoross.io.

**Comment by michfuer** [comment]
Excellent. Thanks!
