### ISSUE TITLE
Documentation for running with SimpleHTTPServer is wrong

### ISSUE THREAD

**Issue by frioux** [Netflix/vector#17]
I saw this on the blog post but it might also be in the docs somewhere.  The post says:

      You can also run Vector with Python's SimpleHTTPServer:

      $ cd Vector
      $ python -m SimpleHTTPServer 8080

      Then open Vector on your browser:

      http://localhost:8080

It should say:

      You can also run Vector with Python's SimpleHTTPServer:

      $ cd Vector/app
      $ python -m SimpleHTTPServer 8080

      Then open Vector on your browser:

      http://localhost:8080

**Comment by spiermar** [comment]
Thanks @frioux ! Just updated it!
