### ISSUE TITLE
Update the documentation for new pcp source repo

### ISSUE THREAD

**Issue by sofianinho** [Netflix/vector#171]
Hello,

I just noticed that the old `git://git.pcp.io/pcp` repo for pcp does not work anymore.
```
$ git clone git://git.pcp.io/pcp
Cloning into 'pcp'...
fatal: remote error: 
  Repository not found.
```
The new one seems to be the github based repo `https://github.com/performancecopilot/pcp`. The documentation and installation instructions on http://vectoross.io/docs/installing-performance-co-pilot.html and elsewhere should be updated to reflect this.

Thanks

**Comment by 001101** [comment]
would be also helpful that centos and maybe other red hat derivates already have pcp on their repo, so this simple command must be added:

yum install pcp

**Comment by spiermar** [comment]
Documentation was updated. http://vectoross.io/docs/installing-performance-co-pilot.html
