### ISSUE TITLE
Invalid Context

### ISSUE THREAD

**Issue by airforceboricua** [Netflix/vector#18]
Trying to connect to local host and I'm getting this:

"Invalid context. Please update host to resume operation."

Am I missing something?

**Comment by Rking788** [comment]
same.

**Comment by batasrki** [comment]
Have you validated that the PCP is running, including the pmwebd and that the port 44323 is open?

**Comment by Rking788** [comment]
PCP is running, it doesn't look like pmwebd is running though.

**Comment by Rking788** [comment]
Looks like the pmwebd service was not being installed. Found out that I needed to install the libmicrohttpd10 package on ubuntu, reconfigure, make, make install. Started the service.

Seems to be working now. Thanks @batasrki

**Comment by airforceboricua** [comment]
Thanks for the responses but this is what I am getting now:
"Failed fetching context from host. Try updating the hostname."

I have followed everything here http://techblog.netflix.com/2015/04/introducing-vector-netflixs-on-host.html?m=1 and am only trying to test this on the same server where I performed the installation.  Is that not possible?  What am I missing?

**Comment by airforceboricua** [comment]
I see my problem.  pmwebd is not starting.  @Rking788 how did you install and configure it?

**Comment by Rking788** [comment]
not sure what OS you are on, but what I had to do was install the libmicrohttpd10 package on Ubuntu. Then re-run the configure, make, and make install commands as described in the PCP installation instructions. 

pmwebd is not compiled or installed if libmicrohttpd is missing. (See the performancecopilot/pcp#5 issue I linked above).

**Comment by airforceboricua** [comment]
I'm on ubuntu 14.04, I've done that and the pmwebd service still does not run.  Thanks for the reply.

**Comment by Rking788** [comment]
Did you recompile PCP? Two things:

1.) Check if pmwebd is installed at /etc/init.d/pmwebd, if it is NOT then there were other build issues.
2.) If it is in /etc/init.d you probably need to run `service pmwebd start` to start the service (probably as root)

**Comment by airforceboricua** [comment]
Yup, I've done that and the service still will not start even after recompiling and starting the service:
"Checking for pmwebd: stopped"

**Comment by batasrki** [comment]
Actually, it looks as if on 14.04, the build process doesn't make a pmwebd binary. If you check top/htop for processes starting with *pm*, you'll notice that **pmcd** runs from /usr/libexec/pcp/bin. If you list contents of that directory, you'll notice there's no pmwebd

**Comment by fche** [comment]
See if your build tree contains a pmwebd binary (src/pmwebapi).  If not, the top-level config.log should give a hint as to why - what's missing (libmicrohttpd10-dev or something like that).  If yes, you can just run it by hand for initial testing:

    % pmwebd -v

**Comment by Rking788** [comment]
It was not originally building the pmwebd binary at first, but as I mentioned, after installing libmicrohttpd10 and rebuilding, I now have the pmwebd binary.

**Comment by batasrki** [comment]
@Rking788 I installed libmicrohttpd10 and libmicrohttpd-dev, and then reconfigured, re-maked and re-installed. I'll try again, but it didn't work the first time.

**Comment by batasrki** [comment]
Yep, did it again and same result

**Comment by airforceboricua** [comment]
same here

**Comment by batasrki** [comment]
I added an issue here, https://github.com/performancecopilot/pcp/issues/9

**Comment by airforceboricua** [comment]
thanks!

**Comment by Rking788** [comment]
You should try what @fche suggested.

**Comment by Rking788** [comment]
you should try what @fche suggested. it could be another missing dependency on your machine other than libmicrohttpd

**Comment by batasrki** [comment]
@fche @Rking788 config.log doesn't show any errors, the git repository has a pmwebapi directory, but there are no binaries. Where is the build tree located? Is that the same as the git repository?

**Comment by fche** [comment]
We've found out that pkgconfig (a tool used during pcp build-configuration) is sometimes missing, and is needed for libmicrohttpd to be found.  Please 'apt-get install pkgconfig' and try again.  (Thanks frew.)

**Comment by batasrki** [comment]
OK, I got it. It was ```pkg-config```. Also, I had to install ```libmicrohttpd-dev```. But after doing that and re-compiling, I have a working setup. Thanks, @Rking788 and @fche

**Comment by airforceboricua** [comment]
That did it!  Thank you so much!

**Comment by pl1ght** [comment]
@batasrki Thanks on the libmicrohttpd-dev.  Fixed my issues.

**Comment by spiermar** [comment]
@airforceboricua all good now then??

**Comment by airforceboricua** [comment]
yes, all good

**Comment by cremersstijn** [comment]
how can you install pmwebd on mac os x?

**Comment by fche** [comment]
@cremersstijn sorry, don't have access; in theory it should Just Work if you have pkgconfig & libmicrohttpd & c++ compilers installed.

**Comment by shamik** [comment]
I went through the installation process and ended-up installing all necessary apps, including the missing one mentioned in the thread. In spite of that. I keep on getting " Error! Failed fetching context from host. Try updating the hostname." I've the required ports open, so the firewall issues are being ruled out. Is there a log which I can refer to ?

**Comment by phanisrinivas** [comment]
I have the same issue on mac. Can some please point me how to resolve the issue?

**Comment by spiermar** [comment]
@shamik @phanisrinivas JavaScript console on the browser. Can you send us the error message?

**Comment by shamik** [comment]
@spiermar , thanks for looking into this. Here's the error log when the following call is being made and the corresponding error is being returned.

http://ec2-xx-xx-xxx-xxx.us-west-1.compute.amazonaws.com:44323/pmapi/context?hostspec=localhost&polltimeout=600

Error fetching context.
e/<()angular.min.js (line 102)
updateContextErrorCallback()services.js (line 292)
updateContext/<()services.js (line 311)
k/g.error/<()angular.min.js (line 81)
b = Object { status=0, config={...}, data=null, more...}
f/<()angular.min.js (line 112)
Pe/this.$get</n.prototype.$eval()angular.min.js (line 126)
a = function()
b = undefined
Pe/this.$get</n.prototype.$digest()angular.min.js (line 123)
Pe/this.$get</n.prototype.$apply()angular.min.js (line 126)
a = undefined
l()angular.min.js (line 81)
b = -1
c = null
d = null
e = ""
M()angular.min.js (line 85)
a = l(b, c, d, e)
d = -1
e = null
f = null
g = ""
wf/</e()angular.min.js (line 86)
	

...log||E;a=!1;try{a=!!e.apply}catch(l){}return a?function(){var a=[];r(arguments,f...

angular.min.js (line 102)

Also, I've noticed the following WARNING .


Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ec2-xx-xx-xxx-xxx.us-west-1.compute.amazonaws.com:44323/pmapi/context?hostspec=localhost&polltimeout=600. This can be fixed by moving the resource to the same domain or enabling CORS.

I'm running both Vector and PCP in the same instance. Can that be a problem ?

**Comment by spiermar** [comment]
@shamik you need pcp 3.10 to have the CORS header and completely avoid this problem. Running PCP and Vector on the same instance should't be a problem. Are you serving Vector via pmwebd or another web server? You might run into CORS issues if you are accessing Vector on the same instance, but different ports.

**Comment by phanisrinivas** [comment]
My issue was that pmpweb is not installed. I have downloaded pcp installer for mac. But it doesn't come with pmpweb. And also I am unable to compile and install using pcp sources.

**Comment by shamik** [comment]
@spiermar  I've pcp 3.10.4 running which I had build from source. So, I'm guessing the CORS header is included, is there a place where I can verify ? I'm serving Vector via pmwebd. I didn't get last part, "You might run into CORS issues  if you are accessing Vector on the same instance, but different ports." Can you please elaborate? I'm running Vector using python on port 8080, while pmwebd is running on 44323

**Comment by spiermar** [comment]
@fche can probably help you @phanisrinivas

**Comment by spiermar** [comment]
@shamik I mean that serving Vector from the same instance, but different port would not solve the CORS issue by itself. There is a simple way of checking this. Make a request to get the context:

/pmapi/context?hostspec=localhost&polltimeout=600

And check for the following header.

Access-Control-Allow-Origin → *

If it's not there, there's something wrong.

**Comment by fche** [comment]
@phanisrinivas macos builds of pcp+pmwebd are a work in progress AIUI.
@shamik was probably using relatively old pcp/pmwebd.

**Comment by phanisrinivas** [comment]
Thanks @fche . Do you have any idea when it might be available? Is there a way to keep track of it?

**Comment by fche** [comment]
@phanisrinivas what do you know, this may do the trick ftp://ftp.pcp.io/projects/pcp/download/mac/

**Comment by fche** [comment]
@shamik, by the way, if you're "serving vector via pmwebd", then you don't need the python / port-8080 stuff at all.

**Comment by phanisrinivas** [comment]
@fche , I installed pcp-3.10.4-1.dmg only, but I think it is not coming along with pmwebd. Because in] vector, I am getting the following error

http://localhost:44323/pmapi/context?hostspec=localhost&polltimeout=600 net::ERR_CONNECTION_REFUSED

I could see pmchart application ,but pmwebd is not running.

**Comment by fche** [comment]
@phanisrinivas I'm not familiar with macos or that build of pcp, but the pmwebd program may need to be manually started.

**Comment by natoscott** [comment]
@phanisrinivas I've put a pcp-3.10.4-2.dmg build on ftp.pcp.io which includes a static-linked pmwebd binary:
ftp://ftp.pcp.io/projects/pcp/download/mac/pcp-3.10.4-2.dmg

**Comment by phanisrinivas** [comment]
Thanks @natoscott . I will install and try.

**Comment by siliconprime-quangnguyen** [comment]
Hi, I am getting the CORS issue too. I start Vector by python with port 8080 so that is the problem I think. But can anybody tell me how to "serving vector via pmwebd"?
P/s: I am in Linux.
Thanks.

**Comment by fche** [comment]
You can install the vector dist files under a directory for service by pmwebd.  See the "Running on PMWEBD" section at https://github.com/Netflix/vector/wiki/Getting-Started

**Comment by spiermar** [comment]
CORS shouldn't be a problem anymore. pmwebd should return '*' to all requests if I'm not mistaken. Let me know if @fche  suggestion doesn't work.

**Comment by anil11392** [comment]
Flamegraph is not being generated when i click on "Generate flame graph" , i am getting the success generic.systack requested message, but when i open the the flame graph it giving error "PMWEBD error, code -22: Invalid argument" . I tried to run systack.sh with sudo and Systack directory and sysstack.svg is being created. is there anything am i missing? not able to generate flame graph with out running the script as a sudo user. my pmdas path is /usr/lib/pcp/pmdas
