### ISSUE TITLE
Feature request: configurable widget sets

### ISSUE THREAD

**Issue by ms4720** [Netflix/vector#184]
different problems require different views on the system, same with different sites.  It would be very handy if 'Default widgets' turned into a "widget sets" menu that could be configured by the site and came with some reasonable sets shipped.  Something like:

Widget sets:
- default 
- docker 
- java 
- all charts 
- ...

**Comment by spiermar** [comment]
This might be tied to #69

**Comment by ms4720** [comment]
look like it is
