### ISSUE TITLE
bcc pmda widgets

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#186]
- [x] biolatency - as input for a latency heat map
- [x] biotop - as input for a live table or line chart of per-process I/O time
- [x] tcplife - as input for a table of sessions details
- [x] ext4dist/xfsdist/zfsdist - as input for a latency heat map
- [x] biosnoop - as input (end time, latency, type: R or W) for a scatter plot: completion time vs latency, and coloring reads red and writes blue
- [x] biosnoop - as input (end time, device, offset) for an offset heat map: showing per-device access patterns
- [x] execsnoop - as input for a table of process details
- [x] tcpretrans - as input for a table of retransmit details
- [x] tcptop - as input for a live table or line chart of per-process TCP throughput
- [x] runqlat - as input for a latency heat map
- [x] profile - as stack trace input for live CPU flame graphs
- [ ] cachestat - as input for a line graph showing each statistic

**Comment by ms4720** [comment]
Looks very useful, cool
