### ISSUE TITLE
decouple pmwebd & pmcd requirement at target instance

### ISSUE THREAD

**Issue by fche** [Netflix/vector#2]
It could be convenient if the minimum requirement at an instance target is pmcd, i.e., no pmwebd.  This could work if the pmwebd instance that serves pmapi (and perhaps the static webapp assets) is used not just for "/pmapi/context?hostname=localhost" but general "/pmapi/context?hostname=TARGET".  Basically, make it possible to use a central pmwebd as a proxy to remote pmcds.  (This could have negative performance implications, so should probably be optional.)

**Comment by spiermar** [comment]
Adding a "target" hostname parameter should be simple. Just need to think on the best way of displaying it in the UI without breaking the experience.

**Comment by fche** [comment]
Yeah, maybe a checkbox beside the outer hostname, saying whether "local pmcd?"; and if not, then expose another text box where the remote pmcd hostspec can be specified.  That second string could include exciting suffixes like ?user=FOO&pass=BAR&container=DEADBEEF.

**Comment by fche** [comment]
@spiermar - I'd appreciate a review over the fche-issue-2 branch code.

**Comment by spiermar** [comment]
got it @fche I'm merging and testing another change, but as soon as I'm done with that, I'll check it out :-)

**Comment by fche** [comment]
The fche-issue-2a branch was rebased to the new directory layout.

**Comment by fche** [comment]
@spiermar I have been thinking about the way the proposed code automagically sets the pmebapi connection parameters from the window.location, by assuming that the webapp is being served by pmwebd itself.  If that assumption is wrong (so the webapp is being served by python or whatever, on some unusual port), the initial pmwebd connection has to be fixed manually (and the :44323 vectorConfig stuff doesn't come into play).

So ... here's a possibility to let both situations work.  We could add a "Server:" response header into pmwebd, so that the webapp can look for that: if it says "pmwebd", then stay with the given port.  If it doesn't, override the port number to 44323.

**Comment by spiermar** [comment]
2a3e08a8636ad27b061b695622141023dce7c1ab probably solved this.

**Comment by spiermar** [comment]
Is there a doc that I could link to on how to write the hostspec params (&container=FOO, etc)?

**Comment by natoscott** [comment]
There's a man page describing the C API that parses these - __pmParseHostAttrsSpec(3).
A short discussion also exists over in PCPIntro(1) in the "PMCD HOST SPECIFICATION" section.

**Comment by spiermar** [comment]
http://www.pcp.io/man/man3/pmparsehostattrsspec.3.html ?

Have a few comments on the PR too, https://github.com/Netflix/vector/pull/51

**Comment by natoscott** [comment]
@spiermar yes, that's the one.

**Comment by spiermar** [comment]
Great! I'll add a link to the documentation. I'm adding the option to change the default port via UI, but besides that, I think the recent changes cover @fche 's concerns.

**Comment by spiermar** [comment]
Changing port is done. See 6b95f49b9328999a94a9a3b10bca20f7791f6448
