### ISSUE TITLE
Half broken responsiveness intended?

### ISSUE THREAD

**Issue by megamorf** [Netflix/vector#20]
Just out of curiosity: with the 4 column layout the widgets don't wrap onto a new line when the screen width is decreased and instead just get squashed. Is that really the wanted behaviour?

![brokenresponsiveness](https://cloud.githubusercontent.com/assets/1732128/7077901/fcbad872-df14-11e4-8d76-fbbc5a1832e2.png)

**Comment by spiermar** [comment]
Not really, just a use case we never tested. I can have look or if you want, feel free to submit a pull request. :-)

**Comment by spiermar** [comment]
Fixed on 82d52b30911b4aff531e2eb687edf8e505792208.
