### ISSUE TITLE
broken Makefile, and spurious file

### ISSUE THREAD

**Issue by draeath** [Netflix/vector#216]
I'd put in a PR, but I am not 100% on the project structure.

Gulp is no longer part of the build process, but `Makefile` still references it. It also references a removed/moved travis script. While I can fix the build/test statements to make them functional, Travis is a complete mystery to me.

Additionally, I noticed a seemingly spurious empty file, `-`, in the root of the repository. It's been there for a year or so, and should probably be removed. It's very likely this file was created from a shell typo while authoring cc953493.

**Comment by jasonk000** [comment]
@draeath Thanks for the feedback. 

Can you take a look at #217 and see if it solves the issues you raised?

**Comment by draeath** [comment]
Yep, coming in fresh without having looked at that Makefile before I'd have no problems starting a build. Thanks!

**Comment by jasonk000** [comment]
Fixed in bf86121
