### ISSUE TITLE
Not able to add the host and no data turns up on Vector web Console

### ISSUE THREAD

**Issue by vijaykumar0690** [Netflix/vector#30]
Hi team,

I followed the wiki documentation what you have specified to install vector.
I am able to get the vector installed on ec2 machine.
I have installed pcp on the same machine and tried with public dns url.
I am not getting any data on the UI.
When i try to connect the host with pcp -h localhost i am able to connect to pmcd.

Not sure why the data is not showing up.

Regards,
Vijay

**Comment by fche** [comment]
With the current design of vector, the target machine needs to run both pmcd _and_ pmwebd, and the vector webapp must be told of the host name where it can reach that pmwebd.  See also issue #2.

**Comment by meteorfox** [comment]
@vijaykumar0690 As fche suggested make sure you also installed pmwebd.

If you installed pcp from the distro's repo, make sure to also install the pcp-webapi, and that is running.

If you built pcp from source, append the `--with-webapi` flag to the `./configure` command, which will make sure to fail the configure if dependencies are not met when building pmwebd. Then just install the dependencies, and try again.

By default, pmwebd listens on a tcp port 44323.

**Comment by spiermar** [comment]
I also mentioned on the email reply, make sure the ec2 security group allows incoming traffic on port 44323. Not open by default.

**Comment by spiermar** [comment]
@vijaykumar0690 Any updates after opening ports and using the stable branch?

**Comment by vijaykumar0690** [comment]
Hi All,

I downloaded the stable code and installed vector as you suggested by martin. I am able to add the host in the vector console but no data is available on the console
I am still getting the same error.
I am not getting the metrics on the vector dashboard.
As Frank suggested I have installed libmicrohttpd-dev module also. I still don’t find any result’s
Please find the attached scree shot for the same
Looking for further help on the same.
![no_data](https://cloud.githubusercontent.com/assets/10925174/7132210/d03767dc-e2a4-11e4-9661-89885004f7b8.jpg)

**Comment by spiermar** [comment]
Can you paste the responses from PCP? _context,  _indom and _fetch? On Chrome they are under the Network tab.

**Comment by spiermar** [comment]
Any updates on this @vijaykumar0690 ?

**Comment by rguembes** [comment]
I'm noticing the same issue, using Firefox's network response I get JSON.parse:unexpected end of data

**Comment by fche** [comment]
If you're using git vector but older-than-git pcp, you may be hitting issue #31.

**Comment by vijaykumar0690** [comment]
Hi Martin,

I followed the setup again on the fresh machine installed the pcp and git cloned the stable branch as you suggested yesterday.
I am not sure why it did not work yesterday but the same setup started working today.
I am getting the real time data also now.
Let me know if you have made any changes on the vector project.
Please find the attached screen shot for the same
![vector_data](https://cloud.githubusercontent.com/assets/10925174/7166165/b29103e8-e3c9-11e4-9250-c5217a3453bd.jpg)

Regards,
Vijay

**Comment by spiermar** [comment]
Awesome! Let me know if you have any other issues!

**Comment by ldng** [comment]
I have the same issue. Works with Chromium 42 but not in Firefox 37. I'm using pcp-3.10.5 and vector from git.
Pasting console output but stacktrace is useless. I scanned the gulpfile but did not see any dev or debug build option. Maybe you could add sourcemap support to get more meaningful stacktrace in issue reports.

```javascript
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendors-9520a2ac.js:47:10201
"Host: 127.0.0.1" vendors-9520a2ac.js:37:20795
"Host updated." vendors-9520a2ac.js:37:20795
"Context updated." vendors-9520a2ac.js:37:20795
"Dashboard controller initialized with / view." vendors-9520a2ac.js:37:20795
Exception { message: "", result: 2153644038, name: "", filename: "http://localhost:8765/scripts/vendors-9520a2ac.js", lineNumber: 37, columnNumber: 0, inner: null, data: null, stack: "fn/<@http://localhost:8765/scripts/vendors-9520a2ac.js:37:11969
w@http://localhost:8765/scripts/vendors-9520a2ac.js:37:10505
f/u@http://localhost:8765/scripts/vendors-9520a2ac.js:37:9028
l@http://localhost:8765/scripts/vendors-9520a2ac.js:37:26174
u/<@http://localhost:8765/scripts/vendors-9520a2ac.js:37:26346
Xn/this.$get</p.prototype.$eval@http://localhost:8765/scripts/vendors-9520a2ac.js:38:1459
Xn/this.$get</p.prototype.$digest@http://localhost:8765/scripts/vendors-9520a2ac.js:37:32024
Xn/this.$get</p.prototype.$apply@http://localhost:8765/scripts/vendors-9520a2ac.js:38:1728
J/s/<@http://localhost:8765/scripts/vendors-9520a2ac.js:36:6544
r@http://localhost:8765/scripts/vendors-9520a2ac.js:36:18001
J/s@http://localhost:8765/scripts/vendors-9520a2ac.js:36:6465
J@http://localhost:8765/scripts/vendors-9520a2ac.js:36:6751
Q@http://localhost:8765/scripts/vendors-9520a2ac.js:36:6000
@http://localhost:8765/scripts/vendors-9520a2ac.js:40:4270
ae.Callbacks/d@http://localhost:8765/scripts/vendors-9520a2ac.js:29:18202
ae.Callbacks/h.fireWith@http://localhost:8765/scripts/vendors-9520a2ac.js:29:19014
.ready@http://localhost:8765/scripts/vendors-9520a2ac.js:19:11729
pe@http://localhost:8765/scripts/vendors-9520a2ac.js:19:9359
" } vendors-9520a2ac.js:37:20795
r/<() vendors-9520a2ac.js:37
rn/this.$get</<() vendors-9520a2ac.js:37
l() vendors-9520a2ac.js:37
u/<() vendors-9520a2ac.js:37
Xn/this.$get</p.prototype.$eval() vendors-9520a2ac.js:38
Xn/this.$get</p.prototype.$digest() vendors-9520a2ac.js:37
Xn/this.$get</p.prototype.$apply() vendors-9520a2ac.js:38
J/s/<() vendors-9520a2ac.js:36
r() vendors-9520a2ac.js:36
J/s() vendors-9520a2ac.js:36
J() vendors-9520a2ac.js:36
Q() vendors-9520a2ac.js:36
<anonyme> vendors-9520a2ac.js:40
ae.Callbacks/d() vendors-9520a2ac.js:29
ae.Callbacks/h.fireWith() vendors-9520a2ac.js:29
.ready() vendors-9520a2ac.js:19
pe() vendors-9520a2ac.js:19

"Error fetching context." vendors-9520a2ac.js:37:20795
r/<() vendors-9520a2ac.js:37
g() app-67ac572a.js:137
m/<() app-67ac572a.js:137
l() vendors-9520a2ac.js:37
u/<() vendors-9520a2ac.js:37
Xn/this.$get</p.prototype.$eval() vendors-9520a2ac.js:38
Xn/this.$get</p.prototype.$digest() vendors-9520a2ac.js:37
Xn/this.$get</p.prototype.$apply() vendors-9520a2ac.js:38
J/s/<() vendors-9520a2ac.js:36
r() vendors-9520a2ac.js:36
J/s() vendors-9520a2ac.js:36
J() vendors-9520a2ac.js:36
Q() vendors-9520a2ac.js:36
<anonyme> vendors-9520a2ac.js:40
ae.Callbacks/d() vendors-9520a2ac.js:29
ae.Callbacks/h.fireWith() vendors-9520a2ac.js:29
.ready() vendors-9520a2ac.js:19
pe() vendors-9520a2ac.js:19

Use of getPreventDefault() is deprecated. Use defaultPrevented instead. vendors-9520a2ac.js:30:0
Ignoring get or set of property that has [LenientThis] because the "this" object is incorrect. script.js:3503:0
"Interval updated." vendors-9520a2ac.js:37:20795
```

**Comment by spiermar** [comment]
Can you check the network requests to PCP? What is the response for the context request?

**Comment by rbramwell** [comment]
Had a similar issue today. `sudo service pcp status` revealed:
```bash
...
Aug 04 03:59:31 redacted systemd[1]: Starting LSB: Legacy control for PCP daemons...
Aug 04 03:59:32 redacted pcp[6486]: /etc/init.d/pmcd: 37: .: Can't open /usr/share/pcp/lib/rc-proc.sh
Aug 04 03:59:32 redacted pcp[6486]: /etc/init.d/pmlogger: 37: .: Can't open /usr/share/pcp/lib/rc-proc.sh
Aug 04 03:59:32 redacted systemd[1]: Started LSB: Legacy control for PCP daemons.
```

The solution:
```bash
sudo chmod +x /usr/share/pcp/lib/rc-proc.sh
sudo service pcp restart
```

Then `sudo service pcp status` no longer displays that there is an issue, and connecting to the host using Vector is successful.
