### ISSUE TITLE
HTTP 503 for /_indom request with multiple instances 

### ISSUE THREAD

**Issue by meteorfox** [Netflix/vector#31]
It seems there's a maximum for the number of instances that can be fetch in a single /_indom request. pmwebd fails the assertion  `num_instances < max_num_instances` and exits.

@fche Is there a technical limitation to have such a small maximum?

Note: Tags `<client>` and `<host>` has been included to remove sensitive info
```
[Mon Apr 13 18:28:51] pmwebd(8855): pmwebd
        Started daemon on IPv4 TCP port 44323
        Started daemon on IPv6 TCP port 44323
        Verbosity level 2
        Using libmicrohttpd 0.9.33
        PMAPI prefix /pmapi
        Remote context creation requests enabled
        Archive base directory: .
        Graphite API disabled
        Graphite API Cairo graphics rendering compiled-in
        Periodic client statistics dumped roughly every 300s
        Using up to 24 auxiliary threads
[Mon Apr 13 18:28:56] pmwebd(8855): [<client>:39373] HTTP/1.1 GET /pmapi/context hostspec=localhost polltimeout=600
[Mon Apr 13 18:28:56] pmwebd(8855): context PM_CONTEXT_HOST localhost (<host>) (web66857211=pm0) created, expires after 300s
[Mon Apr 13 18:29:01] pmwebd(8855): [<client>:39373] HTTP/1.1 GET /pmapi/66857211/_fetch names=kernel.all.cpu.sys,kernel.all.cpu.user,hinv.ncpu,kernel.percpu.cpu.sys,kernel.percpu.cpu.user,kernel.all.runnable,kernel.all.load,network.interface.in.bytes,network.interface.out.bytes,network.tcpconn.established,network.tcpconn.time_wait,network.tcpconn.close_wait,network.interface.in.packets,network.interface.out.packets,network.tcp.retranssegs,network.tcp.timeouts,network.tcp.listendrops,network.tcp.fastretrans,network.tcp.slowstartretrans,network.tcp.syncretrans,mem.util.cached,mem.util.used,mem.util.free,mem.util.bufmem,mem.vmstat.pgfault,mem.vmstat.pgmajfault,kernel.all.pswitch,disk.dev.read,disk.dev.write,disk.dev.read_bytes,disk.dev.write_bytes,disk.dev.avactive,disk.dev.read_rawactive,disk.dev.write_rawactive
[Mon Apr 13 18:29:03] pmwebd(8855): [<client>:39373] HTTP/1.1 GET /pmapi/66857211/_indom instance=-1 name=kernel.all.cpu.sys
[Mon Apr 13 18:29:03] pmwebd(8855): [<client>:39385] HTTP/1.1 GET /pmapi/66857211/_indom instance=-1 name=kernel.all.runnable
[Mon Apr 13 18:29:03] pmwebd(8855): [<client>:39382] HTTP/1.1 GET /pmapi/66857211/_indom instance=-1 name=kernel.all.cpu.user
[Mon Apr 13 18:29:03] pmwebd(8855): [<client>:39373] HTTP/1.1 GET /pmapi/66857211/_indom instance=1,5,15 name=kernel.all.load
[Mon Apr 13 18:29:03] pmwebd(8855): [<client>:39386] HTTP/1.1 GET /pmapi/66857211/_indom instance=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 name=kernel.percpu.cpu.user
pmwebd: pmwebapi.cxx:918: int pmwebapi_respond_instance_list(MHD_Connection*, const http_params&, webcontext*): Assertion `num_instances < max_num_instances' failed.

```

**Comment by fche** [comment]
The limit is calculated on-the-fly from the actual textual input, not an a-priori fixed value.  Investigating further.

**Comment by meteorfox** [comment]
From this line here: https://github.com/performancecopilot/pcp/blob/master/src/pmwebapi/pmwebapi.cxx#L896

If understand this code correctly, the `max_num_instances` is set to the length of the string variable `name`, that is `kernel.percpu.cpu.user`, which is 22 characters long, and strlen(indom) == 0, but num_instances is 24.

Is that correct?

**Comment by fche** [comment]
Yup, it should be    strlen(val_instance) + strlen (val_iname)

**Comment by fche** [comment]
http://oss.sgi.com/pipermail/pcp/2015-April/006934.html

**Comment by meteorfox** [comment]
Cool, thanks for the quick turn around. Once, the fix is up I'll pull the changes and test it to confirm.

**Comment by fche** [comment]
The fix has been merged into upstream pcp.

**Comment by meteorfox** [comment]
Confirmed is working, no more 503s. @fche thanks for submitting the patch!

Now all I need is fetching the data for network.(in|out).bytes to be faster. :)

**Comment by meteorfox** [comment]
@spiermar Is this fix included in your deb packages for PCP in bintray? I seem to be hitting this problem, whenever I use your deb packages, instead of upstream pcp, could be a different error though, I just want to double check.

Also you might want to keep an eye out for the newest PCP release, there were some performance improvements (e.g. retrieving Network data from with a large number of NICs), related to some new refactors. [More info](http://oss.sgi.com/bugzilla/show_bug.cgi?id=1067)

**Comment by spiermar** [comment]
Probably not. Haven't touched the binaries since the first batch. What deb version and architecture do you need?

**Comment by meteorfox** [comment]
pcp 3.10.5 should be good enough, I use amd64 (x86_64). Thanks

**Comment by spiermar** [comment]
Ubuntu or Debian?

**Comment by meteorfox** [comment]
Sorry, Ubuntu

**Comment by spiermar** [comment]
Trusty? :-)

**Comment by meteorfox** [comment]
Yup, :)

**Comment by spiermar** [comment]
I'll try to get that sorted. It's the same platform we use here, so easier than finding a precise 32 bit VM around. ;-)

**Comment by spiermar** [comment]
Trusty amd64 is there. https://bintray.com/netflixoss/ubuntu/pcp-trusty/3.10.5/view

**Comment by natoscott** [comment]
We've started putting the release builds of PCP here too if that helps: http://bintray.com/pcp

Planning to  update these as each PCP release is tagged, and across quite a few platforms (rpm, deb, mac, and also including the initial Docker container builds of PCP now, thanks to mgoodwin).

This is our first foray into using bintray, so any feedback would be much appreciated - thanks!

**Comment by spiermar** [comment]
Didn't know that @natoscott ! Thanks! I'll probably remove our deb repos and point the documentation to http://bintray.com/pcp. Is that Ok?

**Comment by natoscott** [comment]
@spiermar - np, we only recently set it up (thanks for the tip!) - and, yep, just fine to point Vector docs there.

**Comment by spiermar** [comment]
Awesome. Will try to get this done this week. ;-)
