### ISSUE TITLE
During ./configure specify --with-webapi

### ISSUE THREAD

**Issue by sstarcher** [Netflix/vector#33]
I followed the docs on a Ubuntu 14.04 system and everything looked like it worked fine, but pmwebd did not get installed.  ./configure will fail silently if certain libraries are missing.  If you specify --with-webapi it will exit if the libraries are not installed during ./configure.

Change
 ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
to
 ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-webapi
in documentation

**Comment by spiermar** [comment]
Thanks @sstarcher ! Just updated the wiki page to reflect this.
