### ISSUE TITLE
CORS Error while loading the context

### ISSUE THREAD

**Issue by marco-hoyer** [Netflix/vector#35]
I've set up pcp-webapi to listen on port 44323 and started pcp at all. When I try to access vector, delivered by httpd on port 80, I see the following error in the javascript console:
```
[Error] XMLHttpRequest cannot load http://myhost.local:44323/pmapi/context?hostspec=localhost&polltimeout=600. Origin http://myhost.local is not allowed by Access-Control-Allow-Origin. (vector, line 0)
````
Since pcp-webapi doesn't set any CORS header, the different port causes the issue. If I disable CORS checking in the browser, vector works fine. Now I'm wondering if there isn't anyone having similar problems. As I can see in the wiki, the desired configuration is also to use different ports. How can this work? Or am I am doing something wrong?

Thanks for any advice.

**Comment by fche** [comment]
pmwebd since 3.10.0ish (2014-10-31) does supply CORS headers on responses to the /pmapi calls.

**Comment by marco-hoyer** [comment]
hmpf, I use 3.9.4 from Scientific Linux 6 repo. But this means that 3.10 is a minimum version requirement for vector!? Otherwise I would need to proxy pcp requests through my webapp.

**Comment by fche** [comment]
It turns out that you can probably use vector even with that old pmwebd, if you serve the static webapp itself via pmwebd (rather than an auxiliary web server) by copying the app/ under some directory, and ensure pmwebd is started with "-R $THAT_DIRECTORY".

**Comment by marco-hoyer** [comment]
Oh, ok, I should definitely have a closer look at the cmwebd configuration options. Thx!
