### ISSUE TITLE
bower install fails to get git://github.com/nickholub/angular-ui-dashboard.git"

### ISSUE THREAD

**Issue by rguembes** [Netflix/vector#36]
bower.json file has configured: "angular-ui-dashboard": "~0.8.2",

bower install fails to get git://github.com/nickholub/angular-ui-dashboard.git"

There is not such project in https://github.com/nickholub/

**Comment by rguembes** [comment]
... sorry seems to be a bower config issue:

git config --global url."http://".insteadOf git://

**Comment by simon-lifelike** [comment]
If someone else stumbles across this issue:

The native git transport uses TCP port 9418, so you have to make sure your firewall accepts connections through this port.
Otherwise I would strongly recommend using http**s** and *NOT* http as @rguembes suggests.
