### ISSUE TITLE
Installing pcp from wiki

### ISSUE THREAD

**Issue by hc000** [Netflix/vector#38]
Hello,

I am following along <a href="https://github.com/Netflix/vector/wiki/Installing-Performance-Co-Pilot">the wiki</a> trying to install pcp. However when I try the apt-get update I get this error.

I am using trusty 14.04 ubuntu, and the url is added correctly in the sources.list file

W: Failed to fetch https://dl.bintray.com/netflixoss/ubuntu/dists/trusty/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

Did the location of the file change or I am missing some steps?

Thanks!

**Comment by meteorfox** [comment]
@hc000 The problem seems to be that adding `deb-src` is not necessary since only binaries are being distributed.

I was able to install it successfully, all I did was comment-out the `deb-src` from `/etc/apt/sources.list`.

I hope that helps.

**Comment by spiermar** [comment]
I did that too. Will update the wiki. Tks.
