### ISSUE TITLE
127.0.0.1 not working as hostname

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#42]

**Comment by fche** [comment]
(Please try it with the issue #2 code; I believe IP addresses work there for both pmwebd and pmcd hops.)

**Comment by spiermar** [comment]
I haven't reproduced it yet with current code. Just got a report and want
to track it.

- Martin

**Comment by spiermar** [comment]
Just tried on a fresh Ubuntu VM and it seems to be working. Closing the issue.

![screen shot 2015-04-24 at 9 37 21 am](https://cloud.githubusercontent.com/assets/2207415/7323725/9a7ba5fe-ea65-11e4-89c1-8f5c2780c2f9.png)
