### ISSUE TITLE
browser slows down with multiple graphs after x minutes 

### ISSUE THREAD

**Issue by arcolife** [Netflix/vector#46]
In my Firefox browser, I've observed that for a period of 2 sec interval 2 min window, when we have multiple graphs within a Vector instance. due to its nature of continuous monitoring and querying data, it starts accumulating a lot of data over time, and starts hanging. 

I guess we should have an option of clearing older data based on the window/interval values supplied (Because that data isn't visible any longer in the graph and can be queried again if a bigger window/interval is selected?). Maybe there are other ways to tackle this, like adjusting resources allotted to the Firefox instance itself?

**Comment by spiermar** [comment]
It's a known fact that drawing many charts with many data points would consume quite a bit of CPU. Data is already purged if it's older than the window size. Let me know if you don't see that happening.
I have an item on my list to profile the app and D3 to try finding improvements, but today it is a constraint, yes. Ultimately it will depend on the JS engine you're using and your CPU. Have you tried with Chrome (V8 engine) to see if there's an improvement?

**Comment by meteorfox** [comment]
@spiermar I captured a timeline with chrome (JSProfiler, and Paint enabled). It seems to me that we need to  improve our layering also, everything is being painted on the same layer, which cause big janks when scrolling, and slows down the paint.

Just load this timeline in Chrome
https://www.dropbox.com/s/axtxldkp1x0pa2n/vector_large_window_js_paint_profile.json?dl=0

**Comment by meteorfox** [comment]
@spiermar While there's a slow full layout and paint that causes scrolls to jank (you can see them at the end of the flame chart), I think the biggest bottleneck seems to be going through the scope.$digest every time there is an event that causes a $digest cycle and goes through each of these nvd3 charts, and makes that frame take over 800 ms to render! 

As you suggested, probably we should look at using straight nvd3 without the directives wrapper. 

Here's a flame chart from the JS Profiler in Chrome.
![vector_scope_digest_ticks](https://cloud.githubusercontent.com/assets/232300/7284631/a8eb0d08-e904-11e4-9d70-fbc2f567a64f.png)

**Comment by arcolife** [comment]
I'll try to bring more evidence to this case, meanwhile, i agree nvd3 would be much more helpful here to get rid of the heavy d3 layering that starts to hang browsers.

@all Thanks for adding value to this issue!

**Comment by spiermar** [comment]
Yepp, noticed the same thing here @meteorfox :-)

**Comment by spiermar** [comment]
closing this since we can track the changes on #47
