### ISSUE TITLE
Popup box of detailed info under next widget box

### ISSUE THREAD

**Issue by BlinderTM** [Netflix/vector#55]
Doing a mouse-over of the most recent data point (right end of the graph), the popup will be below the next box of the next widget.

See the attached Screenshot.

![popup_under_next_widget](https://cloud.githubusercontent.com/assets/12203176/7436843/b8b05528-f051-11e4-8227-e583d15c619d.png)

**Comment by spiermar** [comment]
Should be fixed with https://github.com/novus/nvd3/issues/1187
