### ISSUE TITLE
Support for cross-compiling

### ISSUE THREAD

**Issue by joseii** [Netflix/vector#56]
Hi, 
I am working on a project for IoT and it seems vector would fit quite well to it.
I am trying to cross-compile the code for an arm architecture on a linux machine, however on the config phase (./config --host=linux-arm), the script skips the section to set the ps command when it is "checking the ps style".
Since the variable that sets the ps model is not set, the ps style is unknown and the scripts exits.

My target machine has a busybox, and the ps behavior is different from the system I am compiling the code. 
Does it make sense to cross compile?
I can also cross compile specific versions of ps, grep, whatever I need, but it is not clear to me if these binaries are being used to the compilation part (on my linux machine) or if they they are used to parse the output on my target machine.

**Comment by fche** [comment]
Are you sure you're referring to vector (the web application) vs. pcp (the toolkit)?

**Comment by joseii** [comment]
you are totally right.
