### ISSUE TITLE
Running over https is unsupported

### ISSUE THREAD

**Issue by qix** [Netflix/vector#57]
We're serving vector from `pmwebd` which itself is served over https. Since there are a number of places where `http://` is hard-coded.

The changes I required to get vector running are at: https://github.com/authbox-lib/vector/commit/f7760dadfd5f7b70c2f23e1f8343784578ae4ad3

Obviously those specific ones would not be a great addition to the vector project, but you can use it as a list of the places where `http://` is hard-coded should you wish to implement a better solution.

**Comment by spiermar** [comment]
Thanks @qix ! Simple changes and I'll add it to the next release. Not a great idea to have protocol hardcoded. :-)

**Comment by spiermar** [comment]
@qix included an option to change the protocol  on the $http url string, either via config file or $routeParam. b6fd1a2306c6ac1aa38027d426d4369a1e9b0652
Does that help? Serving from PMWEB over HTTPS should just be a matter of deeplinking hostname to "localhost" and changing the protocol config option to https.

**Comment by spiermar** [comment]
Assuming it's OK. Closing the issue, but I can reopen in case the fix doesn't help with the problem.
