### ISSUE TITLE
Question: Central pmwebd mode

### ISSUE THREAD

**Issue by rfrht** [Netflix/vector#58]
Hello,

In Getting started wiki, it states that it is possible to run in: "1. *Per-node* pmwebd and pmcd", check; that worked flawlessly, __and__ "2. *Central* pmwebd, per-node pmcd".

I really tried to sort out this second method. It is mentioned in the wiki that there's a "drop down `hostspec`" where I can define the target host name, but I couldn't manage to make it show up.

I'm running it deployed to the web server, using the artifacts provided by `https://bintray.com/artifact/download/netflixoss/downloads/vector.tar.gz`.

Can someone please add more detail on this?

Thanks a lot,

- RF.

**Comment by fche** [comment]
The "drop down hostspec" box was added in vector 1.0.1.

**Comment by spiermar** [comment]
@fche is right. it was made available on 1.01. Let me know if you have any problems finding it. ;-)

**Comment by rfrht** [comment]
Yup you guys are right! I downloaded a current version and made it work, in its full glory!

Thanks a lot!!
