### ISSUE TITLE
Build instructions for Linux Amazon AMI in wiki

### ISSUE THREAD

**Issue by johanstenberg92** [Netflix/vector#64]
Hi,

I've just got PCP installed on  the Linux Amazon AMI and it required me to build from source (if there is any better way to do it, please share!).

However to do this, I was really forced to search the web, neither the PCP website or your guides helped me.

If you want to add some text for installing PCP through building it from source, that would be great, or what do you think? I can help with a PR if you like the idea. Thanks for an awesome project otherwise.

**Comment by fche** [comment]
TBH this doesn't seem like a vector issue per se.  PCP build instructions are found e.g. in PCP sources:

https://sourceware.org/git/gitweb.cgi?p=pcpfans.git;a=blob;f=INSTALL

**Comment by johanstenberg92** [comment]
I looked through those, maybe the issue is that the PCP package is not openly available on AMI... However I would argue that if I wasn't truly astonished with the nice GUI of vector, I probably would have given up and gone with a different tool since PCP was horrible to install. Well it's your call if you want it there or not.

**Comment by fche** [comment]
Please consider raising with amazon linux support the availability of pcp binaries.

Please let the PCP team know of any shortcomings you've encountered in the build-from-source instructions: pcp@oss.sgi.com or perhaps https://github.com/performancecopilot/pcp/issues .

**Comment by natoscott** [comment]
@johanstenberg92 re "PCP was horrible to install" - you might be able to use one of the pre-built PCP packages from https://bintray.com/pcp now?  Details here:
http://pcp.io/pipermail/pcp-announce/2015-June/000058.html

If there are other binary packaging formats better suited to Amazon images, let me know and we might be able to ease your pain there.

**Comment by johanstenberg92** [comment]
Hi, @natoscott I got it to build so right now I'm leaving it at that. Just wanted you to know that probably users find it harder to install PCP than setup vector. You can close this issue if you want.
