### ISSUE TITLE
Page content doesn't display correctly

### ISSUE THREAD

**Issue by hardware** [Netflix/vector#65]
Hi,

I have a problem with the static webapp, when i run gulp **serve task**, page content doesn't display correctly in my browser. I tested with Chromium 43 and Firefox 38.0.5, same result :

![screen1](http://i.imgur.com/osSiBpD.png)

Network tab : 

![screen2](http://i.imgur.com/Qhoxw0d.png)

Any ideas ?

**Comment by spiermar** [comment]
Interesting. Are you using the master branch? Any errors in the console?

**Comment by hardware** [comment]
Yes, i use the master branch. No errors in the console except a dependency warning in bower with angular

![screen1](https://i.imgur.com/JWdi08J.png)

- **npm install** : https://meshup.net/paste/?5dff0c8a52ee281e#quZrMMFi1JTxjsZ//i67786+Pp7gTA2K15u1oNGhOPM=
- **bower install** : https://meshup.net/paste/?21eef36354e3c9f6#XR9RzZ3iezVJ8jZ2wZIaRuHIkwmcoTDGOGlizoRitg4=
- **gulp build** : https://meshup.net/paste/?eb0351f418c9ac09#AV+q743VdG6GgSDXvfGQB7Y+w1ZXovSybqBF00IKsww=

I try with Python built-in web server, same problem but no errors in the console :

```
python -m SimpleHTTPServer 8080

Serving HTTP on 0.0.0.0 port 8080 ...
xx.xx.xx.xx - - [08/Jul/2015 08:08:35] "GET / HTTP/1.1" 200 -
xx.xx.xx.xx - - [08/Jul/2015 08:08:35] "GET /styles/vendor-a21bde78.css HTTP/1.1" 200 -
xx.xx.xx.xx - - [08/Jul/2015 08:08:35] "GET /scripts/vendors-daee51bb.js HTTP/1.1" 200 -
xx.xx.xx.xx - - [08/Jul/2015 08:08:36] "GET /scripts/app-9309d63d.js HTTP/1.1" 200 -
xx.xx.xx.xx - - [08/Jul/2015 08:08:36] "GET /styles/main-b5d53ab1.css HTTP/1.1" 200 -
xx.xx.xx.xx - - [08/Jul/2015 08:08:36] "GET /fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 200 -
xx.xx.xx.xx - - [08/Jul/2015 08:08:36] "GET /assets/images/vector_owl.png HTTP/1.1" 200 -
xx.xx.xx.xx - - [08/Jul/2015 08:08:37] "GET /favicon.ico HTTP/1.1" 200 -
```

**gulp serve** :

```
gulp serve

[08:03:04] Working directory changed to /tmp/vector
[08:03:09] Using gulpfile /tmp/vector/gulpfile.js
[08:03:09] Starting 'scripts'...
[08:03:14] all files 139.91 kB
[08:03:14] Finished 'scripts' after 4.68 s
[08:03:14] Starting 'inject'...
[08:03:15] gulp-inject 2 files into index.html.
[08:03:15] gulp-inject 41 files into index.html.
[08:03:15] Finished 'inject' after 1.02 s
[08:03:15] Starting 'watch'...
[08:03:15] Finished 'watch' after 194 ms
[08:03:15] Starting 'serve'...
[08:03:15] Finished 'serve' after 95 ms
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000/
    External: http://xx.xx.xx.xx:3000/
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://xx.xx.xx.xx:3001
 -------------------------------------
[BS] Serving files from: .tmp/serve
[BS] Serving files from: src
connect deprecated res.headerSent: use standard res.headersSent node_modules/browser-sync/node_modules/browser-sync-ui/node_modules/weinre/node_modules/express/node_modules/connect/lib/http.js:149:22
```

**Comment by spiermar** [comment]
Ok. There's something wrong there. The dependency warnings are normal, but I can see that you are depending on angularjs-nvd3-directives, which is not a dependency anymore. Can you try git pull the latest code on master?

**Comment by hardware** [comment]
Oups, for the second try, I switch on the branch 'stable' branch. Same problem with master
 branch.

**Comment by spiermar** [comment]
That's really strange. I can't reproduce it here, but looks like a css style was not applied, apparently bootstrap. Running out of ideas, but can you try clearing the caches? And downloading all dependencies again?

**Comment by Wintersmith** [comment]
I have the exact same issue on a clean install ( with the same dependency warnings ) on a minimal Centos 7.  

FWIW, it renders like that in Safari / Chrome.

**Comment by hardware** [comment]
I tried on Windows / Linux / OSX with latest version of Chromium and Firefox, clear the cache and downloading all dependencies again, same issue.

**Comment by spiermar** [comment]
Ok. Managed to reproduce it here. Checking.

**Comment by spiermar** [comment]
Ok. Exactly what I thought. Bootstrap was missing. For some reason Gulp was not injecting it. Fixed that, but found a couple other things. Committing a fix shortly.

**Comment by spiermar** [comment]
Fixes are in. Can you try again? Couple small outstanding bugs (disable animation and chart no data message alignment), but that shouldn't affect Vector's functionality.

**Comment by spiermar** [comment]
Ok. All small bugs were fixed. ;-)

**Comment by Wintersmith** [comment]
Everything renders properly now, thank you!

**Comment by hardware** [comment]
Perfect, thanks ! :)
