### ISSUE TITLE
container-specific dashboard

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#72]

**Comment by spiermar** [comment]
- [ ] container cpu utilization widget
- [ ] container memory utilization widget
- [ ] container network io utilization widget
- [ ] container disk io utilization widget

**Comment by spiermar** [comment]
@brendangregg let me know if anything else comes to mind in terms of widgets/metrics

**Comment by spiermar** [comment]
@hc000 from the widgets mentioned above, which ones you guys already use at att?

**Comment by hc000** [comment]
container cpu utilization widget
 container memory utilization widget
 container network io utilization widget

i will be pushing them later this week.
