### ISSUE TITLE
throttled cpu widget

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#73]
Utilization is not enough. We need a way of visualizing if a container resource is being throttled, either by a hardware limitation or configured software limit.

**Comment by spiermar** [comment]
- [ ] throttled cpu
- [ ] throttled network io

**Comment by spiermar** [comment]
@brendangregg can you list the metrics that would be necessary to implement this?

**Comment by meteorfox** [comment]
For CPU, according to the [Kernel docs](https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt), perhaps 

```
cpu.stat:
- nr_periods: Number of enforcement intervals that have elapsed.
- nr_throttled: Number of times the group has been throttled/limited.
- throttled_time: The total time duration (in nanoseconds) for which entities
```

**Comment by natoscott** [comment]
@spiermar good timing - I've been working on a console-based tool for reporting on containers.  From a PCP POV, the metric hierarchies that are in some way related to containers are:

- cgroups.*
- proc.*
- containers.*
- network.interface.*
- pmcd.hostname
- filesys.*

(those are all influenced by the --container option too - see http://pcp.io/docs/lab.containers.html for more details)

@meteorfox see src/pmdas/linux_proc/cgroups.c line 584 - those CPU metrics you mentioned are currently missing from PCP, but easily added.

**Comment by natoscott** [comment]
| [...] those CPU metrics you mentioned are currently missing from PCP [...]

pcp master branch now has:

$ pminfo -t cgroup.cpusched 
cgroup.cpusched.shares [Processor scheduler cgroup shares]
cgroup.cpusched.periods [Number of CFS elapsed enforcement intervals]
cgroup.cpusched.throttled [Number of times CFS group was throttled/limited]
cgroup.cpusched.throttled_time [Total time group was throttled/limited]

(will be in pcp-3.10.7)
