### ISSUE TITLE
improve widget creation documentation

### ISSUE THREAD

**Issue by gooodmorningopenstack** [Netflix/vector#77]
Hello there,

It seems to be very hard to get all the necessary information in order to create more widgets.
I know that it's on the PCP side but I propose to add more to the wiki, for example how to retrieve all the metrics names (thanks issue #14)
- Get a context (could be usefull to explain what's that): http://PMWEBD_IP:44323/pmapi/context?hostspec=localhost
- Get the metrics for that context: http://PMWEBD_IP:44323/pmapi/CONTEXT_NUMBER/_metric?

I don't know for sure if it's correct but at least it worked, and I'm struggling to find more information of PMAPI calls, if anyone have more...

Thanks,
Kind regards

**Comment by fche** [comment]
See http://man7.org/linux/man-pages/man3/pmwebapi.3.html for documentation of the web api bridged by pmwebd.

**Comment by grumpycatt** [comment]
Thanks for this, very helpful.

Do you have more details about these lines,

https://github.com/Netflix/vector/blob/2ae3c7e0731913c87196729bffc9fff50288c8e7/src/app/app.widgets.js#L42-L47

Thanks

**Comment by fche** [comment]
That code is far removed from the pmwebapi http calls - now you're asking about vector webapp internals.

**Comment by grumpycatt** [comment]
Yes, I understand that and it's in the process of Vector creation widget which is for me a two steps process.

- Understand and review the PCP implementation via the PMAPI calls (list metrics...)
- Write down some code into app.config.js, which needs to understand clearly what these lines mean

It would lead more people to help at widget creation.

My 2 cents,
Kind regards

**Comment by spiermar** [comment]
Hey @grumpycatt,
Just got back from some time off. Not just widget creation, but overall documentation needs to be improved. In the beginning I've focused on getting some documentation done to get people started with Vector, but didn't have the time to extend that yet.
It's on my list, but I don't have a timeframe just yet. In the mean time, you might want to check out the documentation for  the dashboard framework Vector uses. 

https://github.com/DataTorrent/malhar-angular-dashboard

There you should be able find more details about the configuration parameters.
