### ISSUE TITLE
Bintray release not up to date

### ISSUE THREAD

**Issue by rvernica** [Netflix/vector#78]
Hello,

I am planning to use the Bintray release, but it seems to be one version behind. The latest there is:

> Version 1.0.1 Released Apr 29, 2015 [Link](https://bintray.com/netflixoss/downloads/vector/)

while the latest on Github is newer:

> on Jul 13 v1.0.2 [Link](https://github.com/Netflix/vector/releases)

Is this intentional or has the Bintray release been discontinued?

Thanks!

**Comment by spiermar** [comment]
Just updated it! 

https://bintray.com/netflixoss/downloads/vector/1.0.2/view

**Comment by fche** [comment]
Martin, any chance of updating that and future release tarballs to be the compressed ready-to-deploy "gulp build" dist/ artifacts?

**Comment by spiermar** [comment]
That's what is in Bintray now. Compressed /dist.

**Comment by fche** [comment]
OK, I was going by this one; but that's apparently old.
https://bintray.com/artifact/download/netflixoss/downloads/vector.tar.gz

**Comment by spiermar** [comment]
Yeah, first version. Before creating tasks to generate /dist ;-)
