### ISSUE TITLE
PCP Glider Support (PCP for Windows) Different TCP Port

### ISSUE THREAD

**Issue by hassanbabaie** [Netflix/vector#80]
I got this working on Linux and it’s great but I wanted to use this consistently across both Windows and Linux. Not sure if PCP Glider (PCP for Windows) is supported as I can't correlate the 3.1 Linux version to the Windows version but I’ve noticed it listens on a different TCP Port....

PCP Linux: 44323
PCP Glider (Windows): 44321

Has anyone tried to do this? If so did it work and do I just need to find the config file in Glider that sets the listening port and correct it?

Let me know your thoughts if you can

Hass

**Comment by fche** [comment]
Port 44323 is for pmwebd (json pmapi over http).  Port 44321 is for pmcd (binary pmapi over tcp).  A pmwebd instance can be through as a proxy/relay for a real pmcd - thus the "hostname" vs "hostspec" inputs for vector.  See the "pcp deployment models" / "2. central pmwebd" case for one way to make this work.  https://github.com/Netflix/vector/wiki/Getting-Started

**Comment by hassanbabaie** [comment]
Great, I'll look into this tomorrow. Thanks for the quick response!

**Comment by hassanbabaie** [comment]
Just upgraded to version 1.01 and all working now when using the hostspec option

Thanks again

**Comment by itsginfo** [comment]
Did you by chance find a 1.01 binary?  The latest binary I'm able to source from https://dl.bintray.com/pcp/windows/ is 0.9.11

any feedback is definitely appreciated.

**Comment by spiermar** [comment]
@fche @natoscott ^^

**Comment by natoscott** [comment]
> Did you by chance find a 1.01 binary?
> The latest binary I'm able to source from https://dl.bintray.com/pcp/windows/ is 0.9.11
> any feedback is definitely appreciated.

@itsginfo @spiermar there have not been any native PCP for Windows builds for some time, and those 0.9.11 bits are indeed the last released Windows PCP packages.

Building the latest PCP (and all the bits needed for Vector) for Windows is not a problem.  However, producing working .msi packages is the area where much work remains to bring these back up to a releasable state.  If anyone has time & interest in hacking on this, just lemme know and I can provide more details.

**Comment by hassanbabaie** [comment]
I think so, let me go back and check

**Comment by jbilder** [comment]
I feel I've reach a similar positions as others getting the PCP Glider functioning.  Has anyone devised a solution to do seamless monitoring between Linux/Windows?
