### ISSUE TITLE
Proposed Update to "Getting Started" Guide

### ISSUE THREAD

**Issue by hassanbabaie** [Netflix/vector#81]
https://github.com/Netflix/vector/wiki/Getting-Started

This is just a proposal as it might be more hassel than it's worth but wanted to suggest it. It also looks like others may have done the same as me which is more from rushing through the guide.

When I followed the section "Deploying to a web server (Nginx, Apache)" instead of going to the bintray site to check the URL for the latest version and using that I instead used the script in the example which gave me version 1.0 instead of 1.01. I needed version 1.01 for the Hostspec feature.

Change FROM:

$ sudo apt-get install apache2
$ cd /var/www/html
$ sudo wget https://bintray.com/artifact/download/netflixoss/downloads/vector.tar.gz
$ sudo tar xvzf vector.tar.gz

Change TO

$ sudo apt-get install apache2
$ cd /var/www/html
$ sudo wget https://bintray.com/artifact/download/netflixoss/downloads/1.0.1/vector.tar.gz
$ sudo tar xvzf vector.tar.gz

**Comment by spiermar** [comment]
Updated it! Thanks for the tip @hassanbabaie !
