### ISSUE TITLE
RFE: a url querystring syntax to instantiate an embeddable widget

### ISSUE THREAD

**Issue by fche** [Netflix/vector#84]
It would be nice to be able to embed vector graphs into larger web applications, without all the interactive controls and without all the space taken by default graphs.  Perhaps peers to the existing hostname/hostspec, like &dashboard=  (or even  &metrics=FOO.BAR,FOO.BAR2 to allow random pcp metrics to be drawn), &interval=SECONDS, &retain=SECONDS.

**Comment by spiermar** [comment]
Shouldn't be complicated. From the top of my head, it should be just a matter of creating another page without the menubar and add a flag to the dashboard controller to hide the controls. I'll look into it once I'm done with some of the container features.

**Comment by spiermar** [comment]
Included a new 'embed' view. Try it out and let me know if it works for you @fche. 

http://localhost:3000/#/embed?widgets=kernel.all.cpu,kernel.percpu.cpu,kernel.all.runnable&host=pcpdemo.test.netflix.net:7402&hostspec=localhost

**Comment by fche** [comment]
Nice work!
One suggestion: in embed mode, see if we can drop/hide even the window title / X-control / frame, and just have the raw graph/legend surface?  (The widget likely wouldn't be draggable within a foreign webapp, nor would we want to let it kill itself with the X.)

**Comment by spiermar** [comment]
I'll try to remove it and see what happens. It might be straight forward, or it might require a lot of messing with CSS to make it look right.
