### ISSUE TITLE
display version and git commit # on ui

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#89]

**Comment by spiermar** [comment]
Done on 038ab4b4734336b597f2597894548456bbcea7f0. Let me know if that works @fche @natoscott

**Comment by fche** [comment]
Looks good, thanks Martin.

**Comment by fche** [comment]
BTW, a 'git describe' style output that includes a number-of-commits would be a little bit better, since it lets a person see "progress" at a glance: a growing number of commits since a previous snapshot.
IOW compare:

      '1.0.2 # 34a86f749407'

and

      v1.0.2-34-g34a86f749407

**Comment by spiermar** [comment]
What about 44f1e9953a03f07137832f2900c69560ab6a0fc1?

**Comment by fche** [comment]
lgtm!
