### ISSUE TITLE
reboot.min.css getting 404

### ISSUE THREAD

**Issue by kozdincer** [Netflix/vector#9]
reboot.min.css getting from http://reboot.prod.netflix.net/css/dist/reboot.min.css
and its return code is 404.

**Comment by gustavorauber** [comment]
Try http://netflix.com/css/dist/reboot.min.css instead.

**Comment by kozdincer** [comment]
When i try it, getting 301 moved permanantly;

$ curl -I http://netflix.com/css/dist/reboot.min.css
HTTP/1.1 301 Moved Permanently
cache-control: no-cache, no-store
Content-Type: text/css;charset=UTF-8
Date: Wed, 08 Apr 2015 12:55:52 GMT
Edge-control: no-cache, no-store
Location: https://www.netflix.com/css/dist/reboot.min.css
Server: wwwservice i-406baebd
Set-Cookie: memclid=28db211c-8093-4265-9922-200b860df66d; Domain=.netflix.com; Expires=Thu, 07-Apr-2016 12:55:53 GMT; Path=/
Set-Cookie: tlr=TR|1428497753366; Domain=.netflix.com; Expires=Sat, 02-Apr-2016 12:55:53 GMT
Strict-Transport-Security: max-age=0; includeSubDomains
via: 1.1 i-68caaf94 (us-east-1)
X-Content-Type-Options: nosniff
X-Netflix.nfstatus: 1
X-Originating-URL: http://netflix.com/css/dist/reboot.min.css
X-Xss-Protection: 1; mode=block
Connection: keep-alive

**Comment by gustavorauber** [comment]
You must follow the redirects, try using wget instead. I have fetched the file and am serving it locally.

**Comment by kozdincer** [comment]
When i follow the redirects, i ve fetched a html page.
I think it due to my county (turkey) and try another host which at europe,
but i ve fetch same page.

**Comment by fche** [comment]
We should consider bundling that css file within vector too, so the deployed app is self-contained.

**Comment by kozdincer** [comment]
Yes. If i could download the css file, i would sent a patch about that.

**Comment by fche** [comment]
@kozdincer by the way, I didn't see any _problem_ running vector, without that .css file being available.  In what way does it not seem to be "running properly"?

**Comment by kozdincer** [comment]
@fche You right. Its not to be good description. its just 404 problem. Thanks. I ll fix that sentences.

**Comment by spiermar** [comment]
Just pushed a change to fix it. https://github.com/Netflix/vector/commit/cd382324cbf9ac3eba58714f989a8fa327e94754
