### ISSUE TITLE
meta: need a mailing list

### ISSUE THREAD

**Issue by fche** [Netflix/vector#92]
Planning and joint problem solving would benefit from being hosted on a regular public mailing list instead of just private emails / face-to-face meetings.  While github appears to lack this functionality, you're welcome to use the pcp@oss.sgi.com one, or we could host one somewhere else.

**Comment by spiermar** [comment]
Created a Google Group. Tks @fche 

https://groups.google.com/forum/#!forum/vector-users

**Comment by fche** [comment]
Could you configure the group to be open (so non-members can at least view it)?

**Comment by spiermar** [comment]
Just changed it. Tks @fche
