### ISSUE TITLE
PerfEvent + Flame Graphs

### ISSUE THREAD

**Issue by prashrock** [Netflix/vector#93]
I was able to successfully install PCP and Vector on my Ubuntu 14.04 VM running on x86-64 following the below two guides:

1) https://github.com/Netflix/vector/wiki/Getting-Started
2) https://gist.github.com/rictorres/c0749f4cf548006c94d7

Initially I did not have perfEvent's available within my PCP installation. But after asking my friend Google,  I found that installing "libpfm4-dev" and then re-compile/install PCP did the trick. Now I see below:

```SHELL
root@somewhere:~# ls /var/lib/pcp/pmdas/perfevent/
domain.h  help  Install  perfalloc  perfevent.conf  perfevent-makerewrite.pl  pmdaperfevent  pmns  Remove  root
```

Ok, now how do I get Vector to show me PerfEvent specific Widgets ? Specifically, how can I see  Flame Graphs within Vector ? 

Sorry if this question is a bit rough, my knowledge about Node.JS, JS and Vector by itself is quite elementary.

**Comment by tkowalcz** [comment]
Hi,

I have made it work some time ago. This unfortunately means that I'm using old versions of Vector and other tools (for the record: [1], [2] & [3]).

If you start from current versions of the tools you would have to do at least:

1. Change src/app/app.config.js to enable flame graphs (this will add another widget in 'CPU' group):

```diff
diff --git a/src/app/app.config.js b/src/app/app.config.js
index a7db634..c4e6756 100644
--- a/src/app/app.config.js
+++ b/src/app/app.config.js
@@ -26,7 +26,7 @@
             'hostspec': 'localhost', // Default PMCD hostspec
             'interval': 2,  // Default update interval in seconds
             'window': 2,    // Default graph time window in minutes
-            'enableCpuFlameGraph': false,
+            'enableCpuFlameGraph': true,
             'enableDiskLatencyHeatMap': false
         }).constant('containerConfig', {
             'externalAPI': false, //enable and edit containermetadata.service to call external API to resolve
```

2. Install flamegraph extension for PCP

```
sudo su
yum -y install perf
cd /var/lib/pcp/pmdas/ # might vary depending on PCP install location
mkdir generic
cd generic
git clone https://github.com/spiermar/flamegraph-pmda
echo "m" | sudo ./Install
```

3. Edit /var/lib/pcp/pmdas/generic/systack.sh script so that it matches your environment.

4. If you are running Java you need to install perf map agent (basically tool that will attach to your jvm and download mappings of memory addresses to method names):

```
sudo su
yum -y install cmake
cd /usr/lib/jvm
git clone https://github.com/jrudolph/perf-map-agent
cd perf-map-agent
cmake .
make
```

5.Probably there is more. When generating heat map in vector gui check out `/var/log/pcp/pmcd/generic.log` on target server for any errors. I had to edit sudoers file to replace `Defaults    requiretty` with `Defaults    !requiretty`.

[1] https://github.com/codewise/vector
[2] https://github.com/codewise/perf-map-agent
[3] https://github.com/codewise/flamegraph-pmda

**Comment by spiermar** [comment]
Tks @tkowalcz. Hope this solves the issue for @prashrock. The agent is really crufty but works.

We're working on a better perf agent and better integration with Vector using the new flame graph d3 plugin (https://github.com/spiermar/d3-flame-graph).

**Comment by eschizoid** [comment]
@spiermar I had followed your instructions and event thought when i click *Generate* in Cpu Flame Graph and I get the message `Success! generic.systack requested!` nothing is shown. Any suggestions?

**Comment by spiermar** [comment]
Can you see any errors in the JS console? Or network/page resources?

**Comment by eschizoid** [comment]
Yeah, the console is showing the following message `PMWEBD error, code -22: Invalid argument`

And the Network tab has the following relvant infromation:

````
Remote Address:10.136.30.147:44323
Request URL:http://tapvlskp18.d1.peapod.com:44323/systack/systack.svg
Request Method:GET
Status Code:400 Bad Request
Response Headers
view source
Access-Control-Allow-Origin:*
Content-Length:40
Content-Type:text/plain
Date:Mon, 16 Nov 2015 02:44:16 GMT
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,es;q=0.6
Connection:keep-alive
Cookie:v1st=40E5C52F366C3E3E; peapodCookie20=aa300b%3a13bccbaf317%3a-676ead0a1eW9daH; C3UID-414=13689495161410125221; stype=1; RES_TRACKINGID=52152284138255124; __utma=39595580.409920067.1442155284.1442155284.1442155284.1; __utmc=39595580; __utmz=39595580.1442155284.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=193722920.981789953.1447626762.1447626762.1447626762.1; __utmc=193722920; __utmz=193722920.1447626762.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
Host:tapvlskp18.d1.peapod.com:44323
Referer:http://10.136.30.147:3000/
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
````

**Comment by spiermar** [comment]
Also can you check if the image (systack.svg) is in the server? Should be in the pmwebd shared directory. Looks like the image was not generated. There's probably an error message on the server too.

**Comment by eschizoid** [comment]
I don't see any `systack.svg` file. However pmwebd is showing the following:
``
suspicious resource path /usr/share/pcp/webapps/systack/systack.svg
``

**Comment by spiermar** [comment]
And the file is not there, correct? Anything in the pmda logs? Basically there's a bash script that should generate that file and the log should tell why the file was not generated.

**Comment by eschizoid** [comment]
Correct the file is not there. If I execute `systack.sh` manually, I get the following stack trace:
``
chown: cannot access `/tmp/perf-1735.map': No such file or directory
chown: cannot access `/tmp/perf-2081.map': No such file or directory
chown: cannot access `/tmp/perf-2229.map': No such file or directory
chown: cannot access `/tmp/perf-2311.map': No such file or directory
chown: cannot access `/tmp/perf-2419.map': No such file or directory
Failed to open /tmp/perf-1735.map, continuing without symbols
Failed to open /tmp/perf-2081.map, continuing without symbols
Failed to open /tmp/perf-60663.map, continuing without symbols
Failed to open /tmp/perf-2229.map, continuing without symbols
Failed to open /tmp/perf-2419.map, continuing without symbols
Failed to open /tmp/perf-2311.map, continuing without symbols
Failed to open [vsyscall], continuing without symbols
``

**Comment by spiermar** [comment]
looks like it's failing to generate the java symbol maps, but that shouldn't prevent the image to be generated. no errors after that?

Which PMDA are you using?

https://github.com/codewise/flamegraph-pmda/blob/master/systack.sh
or 
https://github.com/spiermar/flamegraph-pmda/blob/master/systack.sh

**Comment by eschizoid** [comment]
Definitely no errors after that and I'm using the second bash script.

**Comment by tkowalcz** [comment]
Hi @eschizoid. I had a bunch of problems witch each step of the script. What worked for me is removing "1>>/dev/null 2>> /dev/null" etc. from each command inside so that you can see all errors that are generated.

**Comment by tkowalcz** [comment]
@spiermar I am far from being a bash expert but in our system scripts we usually pipe messages to logger "| logger" which is bash interface to syslog. Maybe pcp has similar interface to pipe messages to pcp related logs?

**Comment by eschizoid** [comment]
Thanks @tkowalcz! let me give it a shot.

**Comment by spiermar** [comment]
Was the folded stack file created? $WDIR/perf-cpu-stacks.folded

**Comment by eschizoid** [comment]
@spiermar yes it was

````
-stacks.folded
automount;__GI___munmap;flush_tlb_others_ipi 1
automount;__lll_unlock_wake;_spin_lock 1
cimserver;__select;_spin_unlock_irqrestore 1
cimserver;__select;schedule_hrtimeout_range 1
init;__do_softirq 1
init;finish_task_switch 3
init;native_safe_halt 17242
init;schedule 1
init;tick_nohz_restart_sched_tick 2
init;tick_nohz_stop_sched_tick 3
java;BiasedLocking::revoke_and_rebias 1
java;CardTableExtension::scavenge_contents_parallel 1
java;CodeHeap::find_start 1
java;Dictionary::do_unloading 1
java;HandleMarkCleaner::~HandleMarkCleaner 2
java;InstanceKlass::oop_follow_contents 9
java;InstanceKlass::oop_update_pointers 4
java;InstanceKlass::vtable_length 1
java;JNIHandleBlock::oops_do 1
java;JVM_MonitorWait 3
java;JavaThread::thread_from_jni_environment 1
java;MethodData::clean_method_data 1
java;Monitor::ILock 2
java;Monitor::IWait 1
java;Monitor::unlock 2
java;MutableSpace::used_in_words 1
java;NativeCall::destination 1
java;ObjArrayKlass::oop_follow_contents 1
java;ObjArrayKlass::oop_update_pointers 4
java;ObjectMonitor::enter 2
java;ObjectMonitor::wait 1
java;ObjectSynchronizer::deflate_idle_monitors 1
java;ObjectSynchronizer::wait 1
java;PSParallelCompact::FollowKlassClosure::do_klass 1
java;PSParallelCompact::IsAliveClosure::do_object_b 1
java;PSPromotionManager::drain_stacks_depth 1
java;PSRootsClosurefalse::do_oop 1
java;ParCompactionManager::follow_marking_stacks 7
java;ParMarkBitMap::iterate 5
java;ParMarkBitMap::live_words_in_range 6
java;ParMarkBitMap::mark_obj 9
java;ParallelCompactData::add_obj 4
java;ParallelCompactData::calc_new_pointer 6
java;ParallelTaskTerminator::offer_termination 1
java;PerfLongVariant::sample 1
java;RelocIterator::advance_over_prefix 1
java;SharedRuntime::complete_monitor_locking_C 1
java;SpinPause 2
java;StatSamplerTask::task 1
java;SymbolTable::unlink 1
java;Thread::SpinAcquire 2
java;UpdateOnlyClosure::do_addr 5
java;WatcherThread::run 1
java;[unknown] 33
java;[unknown];[unknown];JVM_MonitorWait;ObjectMonitor::wait;__lll_unlock_wake;_spin_lock 1
java;[unknown];[unknown];JVM_MonitorWait;ObjectMonitor::wait;pthread_cond_timedwait@@GLIBC_2.3.2;__audit_syscall_exit 1
java;[unknown];[unknown];JVM_MonitorWait;ObjectMonitor::wait;pthread_cond_timedwait@@GLIBC_2.3.2;drop_futex_key_refs 1
java;[unknown];[unknown];JVM_MonitorWait;ObjectMonitor::wait;pthread_cond_timedwait@@GLIBC_2.3.2;finish_task_switch 5
java;[unknown];[unknown];JVM_MonitorWait;ObjectMonitor::wait;pthread_cond_timedwait@@GLIBC_2.3.2;futex_wait 1
java;[unknown];[unknown];JVM_MonitorWait;ObjectMonitor::wait;pthread_cond_timedwait@@GLIBC_2.3.2;plist_add 1
java;[unknown];[unknown];Unsafe_Unpark;pthread_cond_signal@@GLIBC_2.3.2;_spin_unlock_irqrestore 1
java;[unknown];[unknown];groups_search 1
java;[unknown];[unknown];kmem_cache_alloc 1
java;[unknown];_spin_unlock_irqrestore 1
java;[unknown];generic_getxattr 1
java;[unknown];render_cap_t 1
java;__GI_____strtoull_l_internal 1
java;__GI___libc_read;snmp_fold_field 1
java;__libc_close;system_call_after_swapgs 1
java;__libc_read 1
java;__libc_recv;finish_task_switch 1
java;__libc_send;_spin_unlock_irqrestore 1
java;__libc_send;ip_queue_xmit 1
java;__libc_send;vmxnet3_xmit_frame 1
java;__lll_unlock_wake;futex_wake 4
java;__poll;tcp_poll 1
java;__pthread_disable_asynccancel 1
java;__vdso_clock_gettime 2
java;__vdso_gettimeofday 1
java;_wordcopy_fwd_aligned 1
java;clock_gettime 2
java;epoll_wait;finish_task_switch 1
java;jni_GetObjectClass 1
java;nmethod::get_deopt_original_pc 1
java;nmethod::oops_do 2
java;objArrayOopDesc::obj_at 1
java;oopDesc* PSPromotionManager::copy_to_survivor_spacefalse 1
java;oop_Relocation::fix_oop_relocation 1
java;os::PlatformEvent::park 2
java;pthread_cond_signal@@GLIBC_2.3.2;_spin_unlock_irqrestore 3
java;pthread_cond_timedwait@@GLIBC_2.3.2 7
java;pthread_cond_timedwait@@GLIBC_2.3.2;__audit_syscall_exit 3
java;pthread_cond_timedwait@@GLIBC_2.3.2;__list_add 1
java;pthread_cond_timedwait@@GLIBC_2.3.2;_spin_unlock_irqrestore 5
java;pthread_cond_timedwait@@GLIBC_2.3.2;finish_task_switch 10
java;pthread_cond_timedwait@@GLIBC_2.3.2;futex_wait 1
java;pthread_cond_timedwait@@GLIBC_2.3.2;futex_wait_queue_me 1
java;pthread_cond_timedwait@@GLIBC_2.3.2;plist_add 1
java;pthread_cond_timedwait@@GLIBC_2.3.2;sysret_audit 1
java;pthread_cond_timedwait@@GLIBC_2.3.2;system_call_after_swapgs 2
java;pthread_mutex_lock 2
java;vframe::sender 1
karaf-wrapper;[unknown];_spin_unlock_irqrestore 1
karaf-wrapper;[unknown];sys_nanosleep 1
karaf-wrapper;__libc_waitpid;do_wait 9
pmwebd;MHD_get_fdset 5
pmwebd;MHD_run@plt 1
pmwebd;[unknown] 11
pmwebd;[unknown];__select;_cond_resched 1
pmwebd;[unknown];__select;audit_syscall_entry 1
pmwebd;[unknown];__select;copy_from_user 1
pmwebd;[unknown];__select;core_sys_select 4
pmwebd;[unknown];__select;do_select 4
pmwebd;[unknown];__select;memset 1
pmwebd;[unknown];__select;poll_select_copy_remaining 1
pmwebd;[unknown];__select;set_fd_set 2
pmwebd;[unknown];__select;tcp_poll 2
pmwebd;__select 4
pmwebd;__select;_cond_resched 1
pmwebd;__select;copy_user_generic 2
pmwebd;__select;copy_user_generic_unrolled 1
pmwebd;__select;core_sys_select 2
pmwebd;__select;do_select 1
pmwebd;__select;memset 1
pmwebd;__select;sysret_signal 1
pmwebd;__select;system_call_after_swapgs 5
salt-minion;PyArg_UnpackTuple 1
salt-minion;PyCFunction_Call 1
salt-minion;PyDict_GetItem 2
salt-minion;PyEval_EvalFrameEx 5
salt-minion;PyEval_EvalFrameEx;__wake_up_bit 1
salt-minion;PyFrame_New 1
salt-minion;PyInt_AsSsize_t@plt 1
salt-minion;PyIter_Next@plt 1
salt-minion;PyObject_Call 1
salt-minion;PyObject_GenericGetAttr 1
salt-minion;PyObject_GetAttr 1
salt-minion;PyObject_Malloc 1
salt-minion;PyTraceBack_Here 1
salt-minion;PyTuple_New 1
salt-minion;[unknown] 8
salt-minion;[unknown];__GI___socket;kmem_cache_alloc 1
salt-minion;[unknown];__libc_fork;get_page 1
salt-minion;_PyObject_GC_Malloc 1
salt-minion;_PyType_Lookup 1
salt-minion;__GI___libc_read;established_get_next 1
salt-minion;_int_malloc 1
salt-minion;_int_malloc;flush_tlb_page 1
salt-minion;sem_wait 1
splunkd;[unknown];__lxstat64;__link_path_walk 1
splunkd;make_request;__do_softirq 1
swapper;__do_softirq 1
swapper;finish_task_switch 1
swapper;ip_local_deliver_finish 1
swapper;native_safe_halt 5695
swapper;net_rx_action 1
swapper;vmxnet3_poll_rx_only 1
swapper;vmxnet3_unmap_tx_buf 1
vmtoolsd;[unknown] 2
vmtoolsd;__libc_disable_asynccancel 1
vmtoolsd;__poll;native_read_tsc 1
wrapper-linux-x;__libc_waitpid;do_wait 1
wrapper-linux-x;__libc_waitpid;sys_wait4 1
````

**Comment by spiermar** [comment]
Besides the missing Java maps, it looks Ok. The only command after that is the perl script that generates de SVG.

$BDIR/flamegraph.pl --color=java --title="CPU Flame Graph (no idle): $HOSTNAME, $TS" < $FOLDED > $SVG

Which apparently is not generating the SVG or error message.

@brendangregg any ideas?

**Comment by inevity** [comment]
PMWEBD error, code -22: Invalid argument  
when generate flamegraph for the system ,i also met the error.
I just restart the pmwebd service ,then i can generate the graph.

**Comment by anil11392** [comment]
After installing pcp and pcp-weapi using debian package no headers files like pmda.h are being generated under /usr/include/pcp/ directory, Could any one please help me in resolving this issue?

**Comment by natoscott** [comment]
@anil11392 libpcp-pmda3-dev contains pmda.h - other, similarly named packages exist for the other header files (libpcp3-dev, libpcp-import1-dev, etc)

**Comment by anil11392** [comment]
While trying to generate flame graph "suspicious resource path /usr/share/pcp/webapps/systack/systack.svg: No such file or directorycis being displayed in /var/log/pcp/pmwebd/pmwebd.log? can anyone please help me

**Comment by tkowalcz** [comment]
The log message is the only problem? Are there any other symptoms? We sometimes get it in our setup, but flame graph generation works. Sometimes vector will redirect me to svg file that does not exist *at that moment* but refreshing it in few seconds helps.

**Comment by anil11392** [comment]
Thankyou @tkowalcz  for responding. i have resolved that issue after running the systack.sh with sudo. but my pmwed is service is not running. when try to restart the service it thrwowing as error message like "pmwebd(13791): Error starting microhttpd daemons on port 44323". Could you please help me? I have put my pmda under /usr/lib/pcp/pmdas

**Comment by fche** [comment]
Do you have a copy of pmwebd already running (on the same port)?  What does /var/log/pcp/pmwebd/pmwebd.log say?

**Comment by anil11392** [comment]
The log file is getting vanished when try to restart pmwebd service? yes pmwebd was running on the same port. I am just restarting the service, It should start apprently.

**Comment by anil11392** [comment]
Thanks @fche. i have resolved pmwebd port issue. i have stopped the pmwebd service and started again and it worked for me.

**Comment by spiermar** [comment]
Hopefully this will help in the future:

http://vectoross.io/docs/cpu-flame-graphs.html

- Martin
