### ISSUE TITLE
charts are not correctly hidden after host change

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#94]
![screen shot 2015-11-04 at 2 00 19 pm](https://cloud.githubusercontent.com/assets/2207415/10954470/5b93eb7c-8302-11e5-8df3-d969b0428b41.png)

steps to reproduce:
1. enter a working hostname
2. wait for charts to appear
3. change hostname to an invalid one
3. charts are just pushed down instead of vanishing

**Comment by hc000** [comment]
I think this is fixed with a4ba2d255e0918459b281a24b85bd97e6f4f09de
